<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OptimFoundation.Core\OptimFoundation.Core.csproj" />
    <ProjectReference Include="..\..\src\OptimFoundation.Gurobi\OptimFoundation.Gurobi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Gurobi110.NET"
               Condition="Exists('$(GUROBI_HOME)\bin\Gurobi110.NET.dll')">
      <HintPath>$(GUROBI_HOME)\bin\Gurobi110.NET.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
