using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using OptimFoundation.Core;
using OptimFoundation.Cplex.Tests.Mocks;
using Xunit;

namespace OptimFoundation.Cplex.Tests.Integration
{
    /// <summary>
    /// 旋鈕值域全覆蓋：對 CplexConfig 的每一顆旋鈕，逐一套用 IBM 官方文件列出的<b>每一個合法值</b>，
    /// 各跑一次真實求解，確認 CPLEX 真的吃得下去。
    /// </summary>
    /// <remarks>
    /// <para>
    /// 與 <see cref="SolverParamCoverageTests"/> 的差別：那支每顆旋鈕只取一個代表值，證明「這條 SetParam 路徑通」；
    /// 本支把值域展開，證明「文件說可以設的值，實際都設得進去」。
    /// </para>
    /// <para>
    /// 值的來源：本機官方文件 <c>CPLEX\Parameters\topics\&lt;ParamName&gt;.html</c> 的 Values 表格
    /// （離散列舉逐值展開）；連續型旋鈕沒有列舉，取文件敘述範圍內的代表值。
    /// </para>
    /// <para>
    /// <b>判定標準是「CPLEX 有沒有拒絕」，不是「解出什麼」</b>。像 NodeLimit=0、IntegerSolutionLimit=1、
    /// UpperCutoff 這類停止條件，求解結果本來就不會是 Optimal，那不算失敗；
    /// 只有 SetParam 或 Solve 丟例外才算這個值不能用。
    /// </para>
    /// </remarks>
    public class SolverParamValueMatrixTests
    {
        private static readonly bool CplexAvailable =
            File.Exists(@"C:\IBM\ILOG\CPLEX_Studio2211\cplex\bin\x64_win64\ILOG.CPLEX.dll");

        // (label, 套用單一旋鈕的單一值)。每一列都對應官方文件列出的一個合法值。
        private static IReadOnlyList<(string Label, Action<CplexConfig> Apply)> Cases =>
            new (string, Action<CplexConfig>)[]
        {
            ("AbsoluteMipGap=1e-6", c => c.AbsoluteMipGap = 1e-6),
            ("AbsoluteMipGap=0.5", c => c.AbsoluteMipGap = 0.5),
            ("AdvancedStart=0", c => c.AdvancedStart = 0),
            ("AdvancedStart=1", c => c.AdvancedStart = 1),
            ("AdvancedStart=2", c => c.AdvancedStart = 2),
            ("AggregationLimitForCut=0", c => c.AggregationLimitForCut = 0),
            ("AggregationLimitForCut=3", c => c.AggregationLimitForCut = 3),
            ("AggregationLimitForCut=10", c => c.AggregationLimitForCut = 10),
            ("AggregatorFill=0", c => c.AggregatorFill = 0L),
            ("AggregatorFill=10", c => c.AggregatorFill = 10L),
            ("AggregatorFill=100", c => c.AggregatorFill = 100L),
            ("AggregatorLimit=-1", c => c.AggregatorLimit = -1),
            ("AggregatorLimit=0", c => c.AggregatorLimit = 0),
            ("AuxiliaryRootThreads=-1", c => c.AuxiliaryRootThreads = -1),
            ("AuxiliaryRootThreads=0", c => c.AuxiliaryRootThreads = 0),
            ("BacktrackTolerance=0", c => c.BacktrackTolerance = 0),
            ("BacktrackTolerance=0.9999", c => c.BacktrackTolerance = 0.9999),
            ("BacktrackTolerance=1", c => c.BacktrackTolerance = 1),
            ("BarrierAlgorithm=0", c => c.BarrierAlgorithm = 0),
            ("BarrierAlgorithm=1", c => c.BarrierAlgorithm = 1),
            ("BarrierAlgorithm=2", c => c.BarrierAlgorithm = 2),
            ("BarrierAlgorithm=3", c => c.BarrierAlgorithm = 3),
            ("BarrierColumnNonzeros=0", c => c.BarrierColumnNonzeros = 0),
            ("BarrierConvergeTol=1e-8", c => c.BarrierConvergeTol = 1e-8),
            ("BarrierConvergeTol=1e-12", c => c.BarrierConvergeTol = 1e-12),
            ("BarrierCorrectionLimit=-1", c => c.BarrierCorrectionLimit = -1L),
            ("BarrierCorrectionLimit=0", c => c.BarrierCorrectionLimit = 0L),
            ("BarrierCrossover=0", c => c.BarrierCrossover = 0),
            ("BarrierCrossover=1", c => c.BarrierCrossover = 1),
            ("BarrierCrossover=2", c => c.BarrierCrossover = 2),
            ("BarrierDisplay=0", c => c.BarrierDisplay = 0),
            ("BarrierDisplay=1", c => c.BarrierDisplay = 1),
            ("BarrierDisplay=2", c => c.BarrierDisplay = 2),
            ("BarrierGrowthLimit=1e12", c => c.BarrierGrowthLimit = 1e12),
            ("BarrierGrowthLimit=1e6", c => c.BarrierGrowthLimit = 1e6),
            ("BarrierIterationLimit=0", c => c.BarrierIterationLimit = 0L),
            ("BarrierIterationLimit=9223372036800000000", c => c.BarrierIterationLimit = 9223372036800000000L),
            ("BarrierObjectiveRange=1e20", c => c.BarrierObjectiveRange = 1e20),
            ("BarrierObjectiveRange=1e15", c => c.BarrierObjectiveRange = 1e15),
            ("BarrierOrdering=0", c => c.BarrierOrdering = 0),
            ("BarrierOrdering=1", c => c.BarrierOrdering = 1),
            ("BarrierOrdering=2", c => c.BarrierOrdering = 2),
            ("BarrierOrdering=3", c => c.BarrierOrdering = 3),
            ("BarrierQcpConvergeTol=1e-7", c => c.BarrierQcpConvergeTol = 1e-7),
            ("BarrierStartAlgorithm=1", c => c.BarrierStartAlgorithm = 1),
            ("BarrierStartAlgorithm=2", c => c.BarrierStartAlgorithm = 2),
            ("BarrierStartAlgorithm=3", c => c.BarrierStartAlgorithm = 3),
            ("BarrierStartAlgorithm=4", c => c.BarrierStartAlgorithm = 4),
            ("BendersFeasibilityCutTol=1e-6", c => c.BendersFeasibilityCutTol = 1e-6),
            ("BendersOptimalityCutTol=1e-6", c => c.BendersOptimalityCutTol = 1e-6),
            ("BendersStrategy=-1", c => c.BendersStrategy = -1),
            ("BendersStrategy=0", c => c.BendersStrategy = 0),
            ("BendersStrategy=1", c => c.BendersStrategy = 1),
            ("BendersStrategy=2", c => c.BendersStrategy = 2),
            ("BendersStrategy=3", c => c.BendersStrategy = 3),
            ("BendersWorkerAlgorithm=0", c => c.BendersWorkerAlgorithm = 0),
            ("BendersWorkerAlgorithm=1", c => c.BendersWorkerAlgorithm = 1),
            ("BendersWorkerAlgorithm=2", c => c.BendersWorkerAlgorithm = 2),
            ("BendersWorkerAlgorithm=3", c => c.BendersWorkerAlgorithm = 3),
            ("BendersWorkerAlgorithm=4", c => c.BendersWorkerAlgorithm = 4),
            ("BendersWorkerAlgorithm=5", c => c.BendersWorkerAlgorithm = 5),
            ("BestBoundInterval=0", c => c.BestBoundInterval = 0L),
            ("BestBoundInterval=1", c => c.BestBoundInterval = 1L),
            ("BestBoundInterval=7", c => c.BestBoundInterval = 7L),
            ("BoundStrengthening=-1", c => c.BoundStrengthening = -1),
            ("BoundStrengthening=0", c => c.BoundStrengthening = 0),
            ("BoundStrengthening=1", c => c.BoundStrengthening = 1),
            ("BqpCuts=-1", c => c.BqpCuts = -1),
            ("BqpCuts=0", c => c.BqpCuts = 0),
            ("BqpCuts=1", c => c.BqpCuts = 1),
            ("BqpCuts=2", c => c.BqpCuts = 2),
            ("BqpCuts=3", c => c.BqpCuts = 3),
            ("BranchDirection=-1", c => c.BranchDirection = -1),
            ("BranchDirection=0", c => c.BranchDirection = 0),
            ("BranchDirection=1", c => c.BranchDirection = 1),
            ("CalculateQcpDuals=0", c => c.CalculateQcpDuals = 0),
            ("CalculateQcpDuals=1", c => c.CalculateQcpDuals = 1),
            ("CalculateQcpDuals=2", c => c.CalculateQcpDuals = 2),
            ("CardinalityLocalSearch=-1", c => c.CardinalityLocalSearch = -1),
            ("CardinalityLocalSearch=0", c => c.CardinalityLocalSearch = 0),
            ("CardinalityLocalSearch=1", c => c.CardinalityLocalSearch = 1),
            ("CardinalityLocalSearch=2", c => c.CardinalityLocalSearch = 2),
            ("CliqueCuts=-1", c => c.CliqueCuts = -1),
            ("CliqueCuts=0", c => c.CliqueCuts = 0),
            ("CliqueCuts=1", c => c.CliqueCuts = 1),
            ("CliqueCuts=2", c => c.CliqueCuts = 2),
            ("CliqueCuts=3", c => c.CliqueCuts = 3),
            ("ClockType=0", c => c.ClockType = 0),
            ("ClockType=1", c => c.ClockType = 1),
            ("ClockType=2", c => c.ClockType = 2),
            ("CloneLog=true", c => c.CloneLog = true),
            ("CloneLog=false", c => c.CloneLog = false),
            ("CoefficientReduction=-1", c => c.CoefficientReduction = -1),
            ("CoefficientReduction=0", c => c.CoefficientReduction = 0),
            ("CoefficientReduction=1", c => c.CoefficientReduction = 1),
            ("CoefficientReduction=2", c => c.CoefficientReduction = 2),
            ("CoefficientReduction=3", c => c.CoefficientReduction = 3),
#pragma warning disable CS0618
            ("ColumnRead=60000", c => c.ColumnRead = 60000),
#pragma warning restore CS0618
            ("ConflictAlgorithm=0", c => c.ConflictAlgorithm = 0),
            ("ConflictAlgorithm=1", c => c.ConflictAlgorithm = 1),
            ("ConflictAlgorithm=2", c => c.ConflictAlgorithm = 2),
            ("ConflictAlgorithm=3", c => c.ConflictAlgorithm = 3),
            ("ConflictAlgorithm=4", c => c.ConflictAlgorithm = 4),
            ("ConflictAlgorithm=5", c => c.ConflictAlgorithm = 5),
            ("ConflictAlgorithm=6", c => c.ConflictAlgorithm = 6),
            ("ConflictDisplay=0", c => c.ConflictDisplay = 0),
            ("ConflictDisplay=1", c => c.ConflictDisplay = 1),
            ("ConflictDisplay=2", c => c.ConflictDisplay = 2),
            ("CoverCuts=-1", c => c.CoverCuts = -1),
            ("CoverCuts=0", c => c.CoverCuts = 0),
            ("CoverCuts=1", c => c.CoverCuts = 1),
            ("CoverCuts=2", c => c.CoverCuts = 2),
            ("CoverCuts=3", c => c.CoverCuts = 3),
            ("CpuMask=off", c => c.CpuMask = "off"),
            ("CpuMask=auto", c => c.CpuMask = "auto"),
            ("CutPasses=-1", c => c.CutPasses = -1L),
            ("CutPasses=0", c => c.CutPasses = 0L),
            ("CutsFactor=-1", c => c.CutsFactor = -1),
            ("CutsFactor=4", c => c.CutsFactor = 4),
            ("CutsFactor=1e75", c => c.CutsFactor = 1e75),
            ("DataCheck=0", c => c.DataCheck = 0),
            ("DataCheck=1", c => c.DataCheck = 1),
            ("DataCheck=2", c => c.DataCheck = 2),
            ("DependencyCheck=-1", c => c.DependencyCheck = -1),
            ("DependencyCheck=0", c => c.DependencyCheck = 0),
            ("DependencyCheck=1", c => c.DependencyCheck = 1),
            ("DependencyCheck=2", c => c.DependencyCheck = 2),
            ("DependencyCheck=3", c => c.DependencyCheck = 3),
            ("DeterministicTimeLimit=1e7", c => c.DeterministicTimeLimit = 1e7),
            ("DisjunctiveCuts=-1", c => c.DisjunctiveCuts = -1),
            ("DisjunctiveCuts=0", c => c.DisjunctiveCuts = 0),
            ("DisjunctiveCuts=1", c => c.DisjunctiveCuts = 1),
            ("DisjunctiveCuts=2", c => c.DisjunctiveCuts = 2),
            ("DisjunctiveCuts=3", c => c.DisjunctiveCuts = 3),
            ("DiveType=0", c => c.DiveType = 0),
            ("DiveType=1", c => c.DiveType = 1),
            ("DiveType=2", c => c.DiveType = 2),
            ("DiveType=3", c => c.DiveType = 3),
            ("DualSimplexPricing=0", c => c.DualSimplexPricing = 0),
            ("DualSimplexPricing=1", c => c.DualSimplexPricing = 1),
            ("DualSimplexPricing=2", c => c.DualSimplexPricing = 2),
            ("DualSimplexPricing=3", c => c.DualSimplexPricing = 3),
            ("DualSimplexPricing=4", c => c.DualSimplexPricing = 4),
            ("DualSimplexPricing=5", c => c.DualSimplexPricing = 5),
            ("EachCutLimit=0", c => c.EachCutLimit = 0),
            ("EachCutLimit=2100000000", c => c.EachCutLimit = 2100000000),
            ("Emphasis=0", c => c.Emphasis = 0),
            ("Emphasis=1", c => c.Emphasis = 1),
            ("Emphasis=2", c => c.Emphasis = 2),
            ("Emphasis=3", c => c.Emphasis = 3),
            ("Emphasis=4", c => c.Emphasis = 4),
            ("Emphasis=5", c => c.Emphasis = 5),
            ("FeasOptMode=0", c => c.FeasOptMode = 0),
            ("FeasOptMode=1", c => c.FeasOptMode = 1),
            ("FeasOptMode=2", c => c.FeasOptMode = 2),
            ("FeasOptMode=3", c => c.FeasOptMode = 3),
            ("FeasOptMode=4", c => c.FeasOptMode = 4),
            ("FeasOptMode=5", c => c.FeasOptMode = 5),
            ("FeasOptRelaxTolerance=1e-6", c => c.FeasOptRelaxTolerance = 1e-6),
            ("FeasibilityPumpHeuristic=-1", c => c.FeasibilityPumpHeuristic = -1),
            ("FeasibilityPumpHeuristic=0", c => c.FeasibilityPumpHeuristic = 0),
            ("FeasibilityPumpHeuristic=1", c => c.FeasibilityPumpHeuristic = 1),
            ("FeasibilityPumpHeuristic=2", c => c.FeasibilityPumpHeuristic = 2),
            ("FeasibilityTol=1e-9", c => c.FeasibilityTol = 1e-9),
            ("FeasibilityTol=1e-6", c => c.FeasibilityTol = 1e-6),
            ("FeasibilityTol=1e-1", c => c.FeasibilityTol = 1e-1),
            ("FileEncoding=ISO-8859-1", c => c.FileEncoding = "ISO-8859-1"),
            ("FileEncoding=UTF-8", c => c.FileEncoding = "UTF-8"),
            ("FlowCoverCuts=-1", c => c.FlowCoverCuts = -1),
            ("FlowCoverCuts=0", c => c.FlowCoverCuts = 0),
            ("FlowCoverCuts=1", c => c.FlowCoverCuts = 1),
            ("FlowCoverCuts=2", c => c.FlowCoverCuts = 2),
            ("FlowPathCuts=-1", c => c.FlowPathCuts = -1),
            ("FlowPathCuts=0", c => c.FlowPathCuts = 0),
            ("FlowPathCuts=1", c => c.FlowPathCuts = 1),
            ("FlowPathCuts=2", c => c.FlowPathCuts = 2),
            ("GomoryCandidateLimit=1", c => c.GomoryCandidateLimit = 1),
            ("GomoryCandidateLimit=200", c => c.GomoryCandidateLimit = 200),
            ("GomoryCuts=-1", c => c.GomoryCuts = -1),
            ("GomoryCuts=0", c => c.GomoryCuts = 0),
            ("GomoryCuts=1", c => c.GomoryCuts = 1),
            ("GomoryCuts=2", c => c.GomoryCuts = 2),
            ("GomoryPassLimit=0", c => c.GomoryPassLimit = 0L),
            ("GubCoverCuts=-1", c => c.GubCoverCuts = -1),
            ("GubCoverCuts=0", c => c.GubCoverCuts = 0),
            ("GubCoverCuts=1", c => c.GubCoverCuts = 1),
            ("GubCoverCuts=2", c => c.GubCoverCuts = 2),
            ("HeuristicEffort=0", c => c.HeuristicEffort = 0),
            ("HeuristicEffort=1", c => c.HeuristicEffort = 1),
            ("HeuristicFrequency=-1", c => c.HeuristicFrequency = -1L),
            ("HeuristicFrequency=0", c => c.HeuristicFrequency = 0L),
            ("ImpliedBoundCuts=-1", c => c.ImpliedBoundCuts = -1),
            ("ImpliedBoundCuts=0", c => c.ImpliedBoundCuts = 0),
            ("ImpliedBoundCuts=1", c => c.ImpliedBoundCuts = 1),
            ("ImpliedBoundCuts=2", c => c.ImpliedBoundCuts = 2),
            ("IntSolFilePrefix=testsol", c => c.IntSolFilePrefix = "testsol"),
            ("IntegerSolutionLimit=1", c => c.IntegerSolutionLimit = 1L),
            ("IntegerSolutionLimit=100", c => c.IntegerSolutionLimit = 100L),
            ("IntegralityTolerance=0", c => c.IntegralityTolerance = 0),
            ("IntegralityTolerance=1e-5", c => c.IntegralityTolerance = 1e-5),
            ("IntegralityTolerance=0.5", c => c.IntegralityTolerance = 0.5),
            ("KappaStatistics=-1", c => c.KappaStatistics = -1),
            ("KappaStatistics=0", c => c.KappaStatistics = 0),
            ("KappaStatistics=1", c => c.KappaStatistics = 1),
            ("KappaStatistics=2", c => c.KappaStatistics = 2),
            ("LiftAndProjectCuts=-1", c => c.LiftAndProjectCuts = -1),
            ("LiftAndProjectCuts=0", c => c.LiftAndProjectCuts = 0),
            ("LiftAndProjectCuts=1", c => c.LiftAndProjectCuts = 1),
            ("LiftAndProjectCuts=2", c => c.LiftAndProjectCuts = 2),
            ("LiftAndProjectCuts=3", c => c.LiftAndProjectCuts = 3),
            ("LinearizationTolerance=1e-3", c => c.LinearizationTolerance = 1e-3),
            ("LocalBranchingHeuristic=true", c => c.LocalBranchingHeuristic = true),
            ("LocalBranchingHeuristic=false", c => c.LocalBranchingHeuristic = false),
            ("LocalImpliedBoundCuts=-1", c => c.LocalImpliedBoundCuts = -1),
            ("LocalImpliedBoundCuts=0", c => c.LocalImpliedBoundCuts = 0),
            ("LocalImpliedBoundCuts=1", c => c.LocalImpliedBoundCuts = 1),
            ("LocalImpliedBoundCuts=2", c => c.LocalImpliedBoundCuts = 2),
            ("LocalImpliedBoundCuts=3", c => c.LocalImpliedBoundCuts = 3),
            ("LowerCutoff=-1e75", c => c.LowerCutoff = -1e75),
            ("LowerCutoff=-100", c => c.LowerCutoff = -100),
            ("LowerObjectiveStop=-1e75", c => c.LowerObjectiveStop = -1e75),
            ("LpFolding=-1", c => c.LpFolding = -1),
            ("LpFolding=0", c => c.LpFolding = 0),
            ("LpFolding=1", c => c.LpFolding = 1),
            ("LpFolding=2", c => c.LpFolding = 2),
            ("LpFolding=3", c => c.LpFolding = 3),
            ("LpFolding=4", c => c.LpFolding = 4),
            ("LpFolding=5", c => c.LpFolding = 5),
            ("MarkowitzTolerance=0.0001", c => c.MarkowitzTolerance = 0.0001),
            ("MarkowitzTolerance=0.01", c => c.MarkowitzTolerance = 0.01),
            ("MarkowitzTolerance=0.99999", c => c.MarkowitzTolerance = 0.99999),
            ("McfCuts=-1", c => c.McfCuts = -1),
            ("McfCuts=0", c => c.McfCuts = 0),
            ("McfCuts=1", c => c.McfCuts = 1),
            ("McfCuts=2", c => c.McfCuts = 2),
            ("MemoryEmphasis=true", c => c.MemoryEmphasis = true),
            ("MemoryEmphasis=false", c => c.MemoryEmphasis = false),
            ("MemoryLimitMb=2048", c => c.MemoryLimitMb = 2048),
            ("MemoryLimitMb=128", c => c.MemoryLimitMb = 128),
            ("MipDisplay=0", c => c.MipDisplay = 0),
            ("MipDisplay=1", c => c.MipDisplay = 1),
            ("MipDisplay=2", c => c.MipDisplay = 2),
            ("MipDisplay=3", c => c.MipDisplay = 3),
            ("MipDisplay=4", c => c.MipDisplay = 4),
            ("MipDisplay=5", c => c.MipDisplay = 5),
            ("MipGap=1e-4", c => c.MipGap = 1e-4),
            ("MipGap=0.05", c => c.MipGap = 0.05),
            ("MipInterval=-1", c => c.MipInterval = -1L),
            ("MipInterval=0", c => c.MipInterval = 0L),
            ("MipInterval=100", c => c.MipInterval = 100L),
            ("MipSearch=0", c => c.MipSearch = 0),
            ("MipSearch=1", c => c.MipSearch = 1),
            ("MipSearch=2", c => c.MipSearch = 2),
            ("MiqcpStrategy=0", c => c.MiqcpStrategy = 0),
            ("MiqcpStrategy=1", c => c.MiqcpStrategy = 1),
            ("MiqcpStrategy=2", c => c.MiqcpStrategy = 2),
            ("MirCuts=-1", c => c.MirCuts = -1),
            ("MirCuts=0", c => c.MirCuts = 0),
            ("MirCuts=1", c => c.MirCuts = 1),
            ("MirCuts=2", c => c.MirCuts = 2),
            ("MpsLongNumerics=true", c => c.MpsLongNumerics = true),
            ("MpsLongNumerics=false", c => c.MpsLongNumerics = false),
            ("MultiObjectiveDisplay=0", c => c.MultiObjectiveDisplay = 0),
            ("MultiObjectiveDisplay=1", c => c.MultiObjectiveDisplay = 1),
            ("MultiObjectiveDisplay=2", c => c.MultiObjectiveDisplay = 2),
            ("NetworkDisplay=0", c => c.NetworkDisplay = 0),
            ("NetworkDisplay=1", c => c.NetworkDisplay = 1),
            ("NetworkDisplay=2", c => c.NetworkDisplay = 2),
            ("NetworkExtractionLevel=1", c => c.NetworkExtractionLevel = 1),
            ("NetworkExtractionLevel=2", c => c.NetworkExtractionLevel = 2),
            ("NetworkExtractionLevel=3", c => c.NetworkExtractionLevel = 3),
            ("NetworkFeasibilityTol=1e-6", c => c.NetworkFeasibilityTol = 1e-6),
            ("NetworkFeasibilityTol=1e-11", c => c.NetworkFeasibilityTol = 1e-11),
            ("NetworkIterationLimit=1000", c => c.NetworkIterationLimit = 1000L),
            ("NetworkOptimalityTol=1e-6", c => c.NetworkOptimalityTol = 1e-6),
            ("NetworkOptimalityTol=1e-11", c => c.NetworkOptimalityTol = 1e-11),
            ("NetworkPricing=0", c => c.NetworkPricing = 0),
            ("NetworkPricing=1", c => c.NetworkPricing = 1),
            ("NetworkPricing=2", c => c.NetworkPricing = 2),
            ("NetworkPricing=3", c => c.NetworkPricing = 3),
            ("NodeAlgorithm=0", c => c.NodeAlgorithm = 0),
            ("NodeAlgorithm=1", c => c.NodeAlgorithm = 1),
            ("NodeAlgorithm=2", c => c.NodeAlgorithm = 2),
            ("NodeAlgorithm=3", c => c.NodeAlgorithm = 3),
            ("NodeAlgorithm=4", c => c.NodeAlgorithm = 4),
            ("NodeAlgorithm=5", c => c.NodeAlgorithm = 5),
            ("NodeCuts=-1", c => c.NodeCuts = -1),
            ("NodeCuts=0", c => c.NodeCuts = 0),
            ("NodeCuts=1", c => c.NodeCuts = 1),
            ("NodeCuts=2", c => c.NodeCuts = 2),
            ("NodeCuts=3", c => c.NodeCuts = 3),
            ("NodeFileStrategy=0", c => c.NodeFileStrategy = 0),
            ("NodeFileStrategy=1", c => c.NodeFileStrategy = 1),
            ("NodeFileStrategy=2", c => c.NodeFileStrategy = 2),
            ("NodeFileStrategy=3", c => c.NodeFileStrategy = 3),
            ("NodeLimit=1000000", c => c.NodeLimit = 1000000L),
            ("NodeLimit=9223372036800000000", c => c.NodeLimit = 9223372036800000000L),
            ("NodePresolve=-1", c => c.NodePresolve = -1),
            ("NodePresolve=0", c => c.NodePresolve = 0),
            ("NodePresolve=1", c => c.NodePresolve = 1),
            ("NodePresolve=2", c => c.NodePresolve = 2),
            ("NodePresolve=3", c => c.NodePresolve = 3),
            ("NodeSelect=0", c => c.NodeSelect = 0),
            ("NodeSelect=1", c => c.NodeSelect = 1),
            ("NodeSelect=2", c => c.NodeSelect = 2),
            ("NodeSelect=3", c => c.NodeSelect = 3),
#pragma warning disable CS0618
            ("NonzeroRead=250000", c => c.NonzeroRead = 250000L),
#pragma warning restore CS0618
            ("NumericalEmphasis=true", c => c.NumericalEmphasis = true),
            ("NumericalEmphasis=false", c => c.NumericalEmphasis = false),
            ("ObjectiveDifference=0", c => c.ObjectiveDifference = 0),
            ("ObjectiveDifference=1", c => c.ObjectiveDifference = 1),
            ("OptimalityTarget=0", c => c.OptimalityTarget = 0),
            ("OptimalityTarget=1", c => c.OptimalityTarget = 1),
            ("OptimalityTarget=2", c => c.OptimalityTarget = 2),
            ("OptimalityTarget=3", c => c.OptimalityTarget = 3),
            ("OptimalityTol=1e-9", c => c.OptimalityTol = 1e-9),
            ("OptimalityTol=1e-6", c => c.OptimalityTol = 1e-6),
            ("OptimalityTol=1e-1", c => c.OptimalityTol = 1e-1),
            ("ParallelMode=-1", c => c.ParallelMode = -1),
            ("ParallelMode=0", c => c.ParallelMode = 0),
            ("ParallelMode=1", c => c.ParallelMode = 1),
            ("ParamDisplay=true", c => c.ParamDisplay = true),
            ("ParamDisplay=false", c => c.ParamDisplay = false),
            ("PolishAfterAbsoluteMipGap=0", c => c.PolishAfterAbsoluteMipGap = 0),
            ("PolishAfterAbsoluteMipGap=1", c => c.PolishAfterAbsoluteMipGap = 1),
            ("PolishAfterDetTime=1e9", c => c.PolishAfterDetTime = 1e9),
            ("PolishAfterDetTime=0", c => c.PolishAfterDetTime = 0),
            ("PolishAfterMipGap=0", c => c.PolishAfterMipGap = 0),
            ("PolishAfterMipGap=0.5", c => c.PolishAfterMipGap = 0.5),
            ("PolishAfterMipGap=1", c => c.PolishAfterMipGap = 1),
            ("PolishAfterNodes=1", c => c.PolishAfterNodes = 1L),
            ("PolishAfterNodes=9223372036800000000", c => c.PolishAfterNodes = 9223372036800000000L),
            ("PolishAfterSolutions=1", c => c.PolishAfterSolutions = 1L),
            ("PolishAfterSolutions=9223372036800000000", c => c.PolishAfterSolutions = 9223372036800000000L),
            ("PolishAfterTime=1e9", c => c.PolishAfterTime = 1e9),
            ("PolishAfterTime=0", c => c.PolishAfterTime = 0),
            ("PopulateLimit=1", c => c.PopulateLimit = 1),
            ("PopulateLimit=20", c => c.PopulateLimit = 20),
            ("PreIndicator=true", c => c.PreIndicator = true),
            ("PreIndicator=false", c => c.PreIndicator = false),
            ("PresolveDual=-1", c => c.PresolveDual = -1),
            ("PresolveDual=0", c => c.PresolveDual = 0),
            ("PresolveDual=1", c => c.PresolveDual = 1),
            ("PresolvePasses=-1", c => c.PresolvePasses = -1),
            ("PresolvePasses=0", c => c.PresolvePasses = 0),
            ("PresolveReduce=0", c => c.PresolveReduce = 0),
            ("PresolveReduce=1", c => c.PresolveReduce = 1),
            ("PresolveReduce=2", c => c.PresolveReduce = 2),
            ("PresolveReduce=3", c => c.PresolveReduce = 3),
            ("PresolveReformulations=0", c => c.PresolveReformulations = 0),
            ("PresolveReformulations=1", c => c.PresolveReformulations = 1),
            ("PresolveReformulations=2", c => c.PresolveReformulations = 2),
            ("PresolveReformulations=3", c => c.PresolveReformulations = 3),
            ("PrimalSimplexPricing=-1", c => c.PrimalSimplexPricing = -1),
            ("PrimalSimplexPricing=0", c => c.PrimalSimplexPricing = 0),
            ("PrimalSimplexPricing=1", c => c.PrimalSimplexPricing = 1),
            ("PrimalSimplexPricing=2", c => c.PrimalSimplexPricing = 2),
            ("PrimalSimplexPricing=3", c => c.PrimalSimplexPricing = 3),
            ("PrimalSimplexPricing=4", c => c.PrimalSimplexPricing = 4),
            ("PriorityOrderType=0", c => c.PriorityOrderType = 0),
            ("PriorityOrderType=1", c => c.PriorityOrderType = 1),
            ("PriorityOrderType=2", c => c.PriorityOrderType = 2),
            ("PriorityOrderType=3", c => c.PriorityOrderType = 3),
            ("Probe=-1", c => c.Probe = -1),
            ("Probe=0", c => c.Probe = 0),
            ("Probe=1", c => c.Probe = 1),
            ("Probe=2", c => c.Probe = 2),
            ("Probe=3", c => c.Probe = 3),
            ("ProbeDetTimeLimit=1e75", c => c.ProbeDetTimeLimit = 1e75),
            ("ProbeDetTimeLimit=1000", c => c.ProbeDetTimeLimit = 1000),
            ("ProbeTimeLimit=1e75", c => c.ProbeTimeLimit = 1e75),
            ("ProbeTimeLimit=10", c => c.ProbeTimeLimit = 10),
            ("QpMakePsd=true", c => c.QpMakePsd = true),
            ("QpMakePsd=false", c => c.QpMakePsd = false),
#pragma warning disable CS0618
            ("QpNonzeroRead=5000", c => c.QpNonzeroRead = 5000L),
#pragma warning restore CS0618
            ("QpToLinear=-1", c => c.QpToLinear = -1),
            ("QpToLinear=0", c => c.QpToLinear = 0),
            ("QpToLinear=1", c => c.QpToLinear = 1),
            ("ReadWarningLimit=0", c => c.ReadWarningLimit = 0L),
            ("ReadWarningLimit=10", c => c.ReadWarningLimit = 10L),
            ("Record=true", c => c.Record = true),
            ("Record=false", c => c.Record = false),
            ("RelativeObjectiveDifference=0", c => c.RelativeObjectiveDifference = 0),
            ("RelativeObjectiveDifference=0.1", c => c.RelativeObjectiveDifference = 0.1),
            ("RelaxedLpPresolve=-1", c => c.RelaxedLpPresolve = -1),
            ("RelaxedLpPresolve=0", c => c.RelaxedLpPresolve = 0),
            ("RelaxedLpPresolve=1", c => c.RelaxedLpPresolve = 1),
            ("RepairTries=-1", c => c.RepairTries = -1L),
            ("RepairTries=0", c => c.RepairTries = 0L),
            ("RepeatPresolve=-1", c => c.RepeatPresolve = -1),
            ("RepeatPresolve=0", c => c.RepeatPresolve = 0),
            ("RepeatPresolve=1", c => c.RepeatPresolve = 1),
            ("RepeatPresolve=2", c => c.RepeatPresolve = 2),
            ("RepeatPresolve=3", c => c.RepeatPresolve = 3),
            ("RinsHeuristicFrequency=-1", c => c.RinsHeuristicFrequency = -1L),
            ("RinsHeuristicFrequency=0", c => c.RinsHeuristicFrequency = 0L),
            ("RltCuts=-1", c => c.RltCuts = -1),
            ("RltCuts=0", c => c.RltCuts = 0),
            ("RltCuts=1", c => c.RltCuts = 1),
            ("RltCuts=2", c => c.RltCuts = 2),
            ("RltCuts=3", c => c.RltCuts = 3),
            ("RootAlgorithm=0", c => c.RootAlgorithm = 0),
            ("RootAlgorithm=1", c => c.RootAlgorithm = 1),
            ("RootAlgorithm=2", c => c.RootAlgorithm = 2),
            ("RootAlgorithm=3", c => c.RootAlgorithm = 3),
            ("RootAlgorithm=4", c => c.RootAlgorithm = 4),
            ("RootAlgorithm=5", c => c.RootAlgorithm = 5),
            ("RootAlgorithm=6", c => c.RootAlgorithm = 6),
#pragma warning disable CS0618
            ("RowRead=30000", c => c.RowRead = 30000),
#pragma warning restore CS0618
            ("Scaling=-1", c => c.Scaling = -1),
            ("Scaling=0", c => c.Scaling = 0),
            ("Scaling=1", c => c.Scaling = 1),
            ("Seed=0", c => c.Seed = 0),
            ("Seed=42", c => c.Seed = 42),
            ("Seed=202009243", c => c.Seed = 202009243),
            ("Seed=2100000000", c => c.Seed = 2100000000),
            ("SiftingAlgorithm=0", c => c.SiftingAlgorithm = 0),
            ("SiftingAlgorithm=1", c => c.SiftingAlgorithm = 1),
            ("SiftingAlgorithm=2", c => c.SiftingAlgorithm = 2),
            ("SiftingAlgorithm=3", c => c.SiftingAlgorithm = 3),
            ("SiftingAlgorithm=4", c => c.SiftingAlgorithm = 4),
            ("SiftingDisplay=0", c => c.SiftingDisplay = 0),
            ("SiftingDisplay=1", c => c.SiftingDisplay = 1),
            ("SiftingDisplay=2", c => c.SiftingDisplay = 2),
            ("SiftingFromSimplex=true", c => c.SiftingFromSimplex = true),
            ("SiftingFromSimplex=false", c => c.SiftingFromSimplex = false),
            ("SiftingIterationLimit=1000", c => c.SiftingIterationLimit = 1000L),
            ("SimplexCrash=-1", c => c.SimplexCrash = -1),
            ("SimplexCrash=0", c => c.SimplexCrash = 0),
            ("SimplexCrash=1", c => c.SimplexCrash = 1),
            ("SimplexDisplay=0", c => c.SimplexDisplay = 0),
            ("SimplexDisplay=1", c => c.SimplexDisplay = 1),
            ("SimplexDisplay=2", c => c.SimplexDisplay = 2),
            ("SimplexDynamicRows=-1", c => c.SimplexDynamicRows = -1),
            ("SimplexDynamicRows=0", c => c.SimplexDynamicRows = 0),
            ("SimplexDynamicRows=1", c => c.SimplexDynamicRows = 1),
            ("SimplexIterationLimit=1000", c => c.SimplexIterationLimit = 1000L),
            ("SimplexIterationLimit=9223372036800000000", c => c.SimplexIterationLimit = 9223372036800000000L),
            ("SimplexLowerObjectiveLimit=-1e75", c => c.SimplexLowerObjectiveLimit = -1e75),
            ("SimplexPerturbationConstant=1e-6", c => c.SimplexPerturbationConstant = 1e-6),
            ("SimplexPerturbationConstant=1e-8", c => c.SimplexPerturbationConstant = 1e-8),
            ("SimplexPerturbationIndicator=true", c => c.SimplexPerturbationIndicator = true),
            ("SimplexPerturbationIndicator=false", c => c.SimplexPerturbationIndicator = false),
            ("SimplexPerturbationLimit=0", c => c.SimplexPerturbationLimit = 0),
            ("SimplexPricingCandidateList=0", c => c.SimplexPricingCandidateList = 0),
            ("SimplexRefactorFrequency=0", c => c.SimplexRefactorFrequency = 0),
            ("SimplexSingularityLimit=0", c => c.SimplexSingularityLimit = 0),
            ("SimplexSingularityLimit=10", c => c.SimplexSingularityLimit = 10),
            ("SimplexUpperObjectiveLimit=1e75", c => c.SimplexUpperObjectiveLimit = 1e75),
            ("SolutionPoolAbsGap=0", c => c.SolutionPoolAbsGap = 0),
            ("SolutionPoolAbsGap=1e75", c => c.SolutionPoolAbsGap = 1e75),
            ("SolutionPoolCapacity=0", c => c.SolutionPoolCapacity = 0),
            ("SolutionPoolCapacity=2100000000", c => c.SolutionPoolCapacity = 2100000000),
            ("SolutionPoolIntensity=0", c => c.SolutionPoolIntensity = 0),
            ("SolutionPoolIntensity=1", c => c.SolutionPoolIntensity = 1),
            ("SolutionPoolIntensity=2", c => c.SolutionPoolIntensity = 2),
            ("SolutionPoolIntensity=3", c => c.SolutionPoolIntensity = 3),
            ("SolutionPoolIntensity=4", c => c.SolutionPoolIntensity = 4),
            ("SolutionPoolRelGap=0", c => c.SolutionPoolRelGap = 0),
            ("SolutionPoolRelGap=1e75", c => c.SolutionPoolRelGap = 1e75),
            ("SolutionPoolReplace=0", c => c.SolutionPoolReplace = 0),
            ("SolutionPoolReplace=1", c => c.SolutionPoolReplace = 1),
            ("SolutionPoolReplace=2", c => c.SolutionPoolReplace = 2),
            ("SolutionType=0", c => c.SolutionType = 0),
            ("SolutionType=1", c => c.SolutionType = 1),
            ("SolutionType=2", c => c.SolutionType = 2),
            ("Sos1Reformulation=-1", c => c.Sos1Reformulation = -1),
            ("Sos1Reformulation=0", c => c.Sos1Reformulation = 0),
            ("Sos1Reformulation=1", c => c.Sos1Reformulation = 1),
            ("Sos2Reformulation=-1", c => c.Sos2Reformulation = -1),
            ("Sos2Reformulation=0", c => c.Sos2Reformulation = 0),
            ("Sos2Reformulation=1", c => c.Sos2Reformulation = 1),
            ("StrongBranchingCandidateLimit=1", c => c.StrongBranchingCandidateLimit = 1),
            ("StrongBranchingCandidateLimit=10", c => c.StrongBranchingCandidateLimit = 10),
            ("StrongBranchingCandidateLimit=2100000000", c => c.StrongBranchingCandidateLimit = 2100000000),
            ("StrongBranchingIterationLimit=0", c => c.StrongBranchingIterationLimit = 0L),
            ("SubMipNodeAlgorithm=0", c => c.SubMipNodeAlgorithm = 0),
            ("SubMipNodeAlgorithm=1", c => c.SubMipNodeAlgorithm = 1),
            ("SubMipNodeAlgorithm=2", c => c.SubMipNodeAlgorithm = 2),
            ("SubMipNodeAlgorithm=3", c => c.SubMipNodeAlgorithm = 3),
            ("SubMipNodeAlgorithm=4", c => c.SubMipNodeAlgorithm = 4),
            ("SubMipNodeAlgorithm=5", c => c.SubMipNodeAlgorithm = 5),
            ("SubMipNodeLimit=1", c => c.SubMipNodeLimit = 1L),
            ("SubMipNodeLimit=500", c => c.SubMipNodeLimit = 500L),
            ("SubMipRootAlgorithm=0", c => c.SubMipRootAlgorithm = 0),
            ("SubMipRootAlgorithm=1", c => c.SubMipRootAlgorithm = 1),
            ("SubMipRootAlgorithm=2", c => c.SubMipRootAlgorithm = 2),
            ("SubMipRootAlgorithm=3", c => c.SubMipRootAlgorithm = 3),
            ("SubMipRootAlgorithm=4", c => c.SubMipRootAlgorithm = 4),
            ("SubMipRootAlgorithm=5", c => c.SubMipRootAlgorithm = 5),
            ("SubMipScaling=-1", c => c.SubMipScaling = -1),
            ("SubMipScaling=0", c => c.SubMipScaling = 0),
            ("SubMipScaling=1", c => c.SubMipScaling = 1),
            ("Symmetry=-1", c => c.Symmetry = -1),
            ("Symmetry=0", c => c.Symmetry = 0),
            ("Symmetry=1", c => c.Symmetry = 1),
            ("Symmetry=2", c => c.Symmetry = 2),
            ("Symmetry=3", c => c.Symmetry = 3),
            ("Symmetry=4", c => c.Symmetry = 4),
            ("Symmetry=5", c => c.Symmetry = 5),
            ("Threads=0", c => c.Threads = 0),
            ("Threads=1", c => c.Threads = 1),
            ("TimeLimit=30", c => c.TimeLimit = 30),
            ("TimeLimit=1e75", c => c.TimeLimit = 1e75),
            ("TreeMemoryLimitMb=1024", c => c.TreeMemoryLimitMb = 1024),
            ("TreeMemoryLimitMb=1e75", c => c.TreeMemoryLimitMb = 1e75),
            ("TuningDetTimeLimit=1e7", c => c.TuningDetTimeLimit = 1e7),
            ("TuningDisplay=0", c => c.TuningDisplay = 0),
            ("TuningDisplay=1", c => c.TuningDisplay = 1),
            ("TuningDisplay=2", c => c.TuningDisplay = 2),
            ("TuningDisplay=3", c => c.TuningDisplay = 3),
            ("TuningMeasure=1", c => c.TuningMeasure = 1),
            ("TuningMeasure=2", c => c.TuningMeasure = 2),
            ("TuningRepeat=1", c => c.TuningRepeat = 1),
            ("TuningRepeat=5", c => c.TuningRepeat = 5),
            ("TuningTimeLimit=1e75", c => c.TuningTimeLimit = 1e75),
            ("TuningTimeLimit=60", c => c.TuningTimeLimit = 60),
            ("UpperCutoff=1e75", c => c.UpperCutoff = 1e75),
            ("UpperCutoff=100", c => c.UpperCutoff = 100),
            ("UpperObjectiveStop=1e75", c => c.UpperObjectiveStop = 1e75),
            ("UsePriorityOrder=true", c => c.UsePriorityOrder = true),
            ("UsePriorityOrder=false", c => c.UsePriorityOrder = false),
            ("VariableSelect=-1", c => c.VariableSelect = -1),
            ("VariableSelect=0", c => c.VariableSelect = 0),
            ("VariableSelect=1", c => c.VariableSelect = 1),
            ("VariableSelect=2", c => c.VariableSelect = 2),
            ("VariableSelect=3", c => c.VariableSelect = 3),
            ("VariableSelect=4", c => c.VariableSelect = 4),
            ("WorkDir=.", c => c.WorkDir = "."),
            ("WriteLevel=0", c => c.WriteLevel = 0),
            ("WriteLevel=1", c => c.WriteLevel = 1),
            ("WriteLevel=2", c => c.WriteLevel = 2),
            ("WriteLevel=3", c => c.WriteLevel = 3),
            ("WriteLevel=4", c => c.WriteLevel = 4),
            ("ZeroHalfCuts=-1", c => c.ZeroHalfCuts = -1),
            ("ZeroHalfCuts=0", c => c.ZeroHalfCuts = 0),
            ("ZeroHalfCuts=1", c => c.ZeroHalfCuts = 1),
            ("ZeroHalfCuts=2", c => c.ZeroHalfCuts = 2),
        };

        /// <summary>
        /// 已知會被 CPLEX 拒絕的值，以及原因。這些不是接線壞掉，是本平台或本模型型態下真的不能用。
        /// </summary>
        private static readonly IReadOnlyDictionary<string, string> ExpectedRejections =
            new Dictionary<string, string>
        {
            ["CpuMask=off"] = "Error 1811：本平台不支援 CPU 綁核；CPLEX Interactive 執行 set cpumask off 同樣被拒",
            ["CpuMask=auto"] = "Error 1811：同上，連官方文件列的預設值 auto 都設不進去",
            ["BendersStrategy=1"] = "Error 2000：模型沒有 Benders 分解註記，這三個值會丟例外而非靜默無效",
            ["BendersStrategy=2"] = "Error 2000：同上",
            ["BendersStrategy=3"] = "Error 2000：同上",
            ["OptimalityTarget=2"] = "Error 1017：值 2（非凸問題求全域最佳）不能用在 mixed-integer 模型上",
        };

        [Fact(DisplayName = "每顆旋鈕的每個官方合法值都能套用並求解")]
        public void EveryDocumentedValue_IsAcceptedByCplex()
        {
            if (!CplexAvailable) return;

            var unexpected = new List<string>();
            var expectedButAccepted = new List<string>(ExpectedRejections.Keys);
            var projectConfig = new ProjectConfig { EnableSolverLog = false };

            foreach (var (label, apply) in Cases)
            {
                try
                {
                    var config = new CplexConfig();
                    apply(config);

                    using var engine = new OptEngine(config, projectConfig);
                    engine.Build();          // Build → Configuration(config)：在此套用該值的 SetParam
                    BuildKnapsack(engine);   // 小型 MILP，讓 MIP 類參數真正生效
                    engine.Solve();
                }
                catch (Exception ex)
                {
                    var msg = (ex.InnerException ?? ex).Message.Split('\n')[0].Trim();
                    if (ExpectedRejections.ContainsKey(label))
                        expectedButAccepted.Remove(label);
                    else
                        unexpected.Add($"{label} → {ex.GetType().Name}: {msg}");
                }
            }

            Assert.True(unexpected.Count == 0,
                $"以下 {unexpected.Count} / {Cases.Count} 個官方合法值被 CPLEX 拒絕，且不在已知清單裡：" +
                Environment.NewLine + string.Join(Environment.NewLine, unexpected));

            // 已知會被拒絕的值若哪天變成可用（換平台、升版），清單就過期了，要主動發現
            Assert.True(expectedButAccepted.Count == 0,
                "以下值列在 ExpectedRejections，但實際上已經可以用了，請更新清單：" +
                Environment.NewLine +
                string.Join(Environment.NewLine,
                    expectedButAccepted.Select(k => $"{k}（原因：{ExpectedRejections[k]}）")));
        }

        /// <summary>3 物品 0/1 背包：max 3a+4b+5c s.t. 2a+3b+4c &lt;= 5。root 即最佳。</summary>
        private static void BuildKnapsack(OptEngine engine)
        {
            var items = new List<string> { "a", "b", "c" };
            engine.BuildBVs<VarS>(items);

            var weight = new Dictionary<string, double> { ["a"] = 2, ["b"] = 3, ["c"] = 4 };
            var value = new Dictionary<string, double> { ["a"] = 3, ["b"] = 4, ["c"] = 5 };

            foreach (var i in items) engine.AddLHS(weight[i], new VarS { S = i });
            engine.CreateLessEqual(5.0, "cap");

            foreach (var i in items) engine.AddLHS(value[i], new VarS { S = i });
            engine.CreateMaximize();
        }
    }
}
