using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace OptimFoundation.Generators
{
    /// <summary>
    /// AutoSets source generator。編譯期把宣告式標記補成完整 class。
    ///
    /// 變數：
    ///     [OptVar(VarType.Binary, "Date:DateTime", "Employee", "Group")]
    ///     public partial class VariableB_ShiftAssign { }
    ///   → : VariableBase + 依序 set 屬性
    ///
    /// 參數：
    ///     [OptParam("Date:DateTime", "Group")]                       // 含 QTY
    ///     [OptParam("Date:DateTime", "Employee", "Group", HasValue = false)]  // 純 key，不含 QTY
    ///     public partial class Parameter_ShiftDemand { }
    ///   → : ParameterBase + set 屬性 + （選擇性）QTY + InitClassBySets 兩個建構子
    ///
    /// attribute / enum 由本 generator 於編譯期注入 OptimFoundation.Modeling namespace，
    /// 使用端只需 <c>using OptimFoundation.Modeling;</c>，不需任何額外組件參考。
    /// 生成 code 以 global:: 全名指向 OptimFoundation.Core 框架型別。
    /// </summary>
    [Generator]
    public sealed class AutoSetsGenerator : IIncrementalGenerator
    {
        private const string VarAttr = "OptimFoundation.Modeling.OptVarAttribute";
        private const string ParamAttr = "OptimFoundation.Modeling.OptParamAttribute";

        private const string VariableBaseFqn = "global::OptimFoundation.Core.VariableBase";
        private const string ParameterBaseFqn = "global::OptimFoundation.Core.ParameterBase";

        // 注入到使用端編譯的 attribute + enum（使用端不需任何額外組件）
        private const string AttributeSource = @"// <auto-generated/>
#nullable enable
using System;

namespace OptimFoundation.Modeling
{
    public enum VarType { Binary, Integer, Continuous }

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class OptVarAttribute : Attribute
    {
        public VarType VarType { get; }
        public string[] Sets { get; }
        public OptVarAttribute(VarType varType, params string[] sets)
        {
            VarType = varType;
            Sets = sets;
        }
    }

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class OptParamAttribute : Attribute
    {
        public string[] Sets { get; }
        /// <summary>true（預設）會生成 QTY 值欄位；純 key 參數設 false。</summary>
        public bool HasValue { get; set; } = true;
        public OptParamAttribute(params string[] sets)
        {
            Sets = sets;
        }
    }
}
";

        /// <summary>
        /// Generator 入口。先注入 attribute 定義，再尋找標記類別並生成對應 partial class。
        /// </summary>
        /// <param name="context"></param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
                ctx.AddSource("OptModelingAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            var vars = context.SyntaxProvider.ForAttributeWithMetadataName(
                    VarAttr,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => ExtractVar(ctx))
                .Where(static m => m is not null);

            var prms = context.SyntaxProvider.ForAttributeWithMetadataName(
                    ParamAttr,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => ExtractParam(ctx))
                .Where(static m => m is not null);

            context.RegisterSourceOutput(vars, static (spc, m) => Emit(spc, m!));
            context.RegisterSourceOutput(prms, static (spc, m) => Emit(spc, m!));
        }

        /// <summary>
        /// 從標記 Class 的 attribute 參數提取資訊，組成 EmitModel 以供後續生成 code。
        /// </summary>
        /// <param name="ctx"></param>
        /// <returns></returns>
        private static EmitModel? ExtractVar(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol symbol || ctx.Attributes.Length == 0) return null;

            var args = ctx.Attributes[0].ConstructorArguments;
            if (args.Length < 2) return null;

            string varType = args[0].Value?.ToString() ?? "Binary";
            string setsCsv = JoinSets(args[1]);

            return new EmitModel(NamespaceOf(symbol), symbol.Name, VariableBaseFqn, setsCsv,
                AddQty: false, AddCtors: false, Meta: $"VarType={varType}");
        }

        /// <summary>
        /// 從標記 Class 的 attribute 參數提取資訊，組成 EmitModel 以供後續生成 code。
        /// </summary>
        /// <param name="ctx"></param>
        /// <returns></returns>
        private static EmitModel? ExtractParam(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol symbol || ctx.Attributes.Length == 0) return null;

            var attr = ctx.Attributes[0];
            if (attr.ConstructorArguments.Length < 1) return null;

            string setsCsv = JoinSets(attr.ConstructorArguments[0]);

            bool hasValue = true;
            foreach (var na in attr.NamedArguments)
                if (na.Key == "HasValue" && na.Value.Value is bool b) hasValue = b;

            return new EmitModel(NamespaceOf(symbol), symbol.Name, ParameterBaseFqn, setsCsv,
                AddQty: hasValue, AddCtors: true, Meta: string.Empty);
        }

        /// <summary>
        /// 將 TypedConstant 中的集合參數連接成 CSV 字串。
        /// </summary>
        /// <param name="arg"></param>
        /// <returns></returns>
        private static string JoinSets(TypedConstant arg)
        {
            if (arg.Kind != TypedConstantKind.Array) return string.Empty;
            var sets = arg.Values.Select(v => v.Value?.ToString() ?? string.Empty).Where(s => s.Length > 0);
            return string.Join("|", sets);
        }

        /// <summary>
        /// 獲取類型符號的命名空間。
        /// </summary>
        /// <param name="s"></param>
        /// <returns></returns>
        private static string NamespaceOf(INamedTypeSymbol s)
            => s.ContainingNamespace.IsGlobalNamespace ? string.Empty : s.ContainingNamespace.ToDisplayString();


        /// <summary>
        /// 根據 EmitModel 生成對應的 partial class 代碼，並添加到編譯輸出中。
        /// </summary>
        /// <param name="spc"></param>
        /// <param name="m"></param>
        private static void Emit(SourceProductionContext spc, EmitModel m)
        {
            string[] sets = m.SetsCsv.Length == 0 ? System.Array.Empty<string>() : m.SetsCsv.Split('|');

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNs = m.Namespace.Length > 0;
            if (hasNs)
            {
                sb.Append("namespace ").Append(m.Namespace).AppendLine();
                sb.AppendLine("{");
            }

            if (m.Meta.Length > 0)
                sb.Append("    // [").Append(m.Meta).AppendLine("] —— 由 AutoSetsGenerator 生成");
            sb.Append("    public partial class ").Append(m.ClassName).Append(" : ").AppendLine(m.BaseFqn);
            sb.AppendLine("    {");

            foreach (var raw in sets)
            {
                var (name, type, isString) = ParseSet(raw);
                if (isString)
                    sb.Append("        public string ").Append(name).AppendLine(" { get; set; } = string.Empty;");
                else
                    sb.Append("        public ").Append(type).Append(' ').Append(name).AppendLine(" { get; set; }");
            }

            if (m.AddQty)
                sb.AppendLine("        public double QTY { get; set; }");

            if (m.AddCtors)
            {
                sb.AppendLine();
                sb.Append("        public ").Append(m.ClassName).AppendLine("(params object[] sets) => InitClassBySets(sets);");
                sb.Append("        public ").Append(m.ClassName).AppendLine("() { }");
            }

            sb.AppendLine("    }");
            if (hasNs) sb.AppendLine("}");

            spc.AddSource($"{m.ClassName}.AutoSets.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        // "Name" → string；"Name:DateTime|date|int|double" → 對應型別
        /// <summary>
        /// 解析 set 定義字串，提取 set 名稱與型別資訊。預設型別為 string，支援 DateTime、int、double。
        /// </summary>
        /// <param name="name"></param>
        /// <param name="type"></param>
        /// <param name="raw"></param>
        /// <returns></returns>
        private static (string name, string type, bool isString) ParseSet(string raw)
        {
            var parts = raw.Split(':');
            string name = parts[0].Trim();
            string t = parts.Length > 1 ? parts[1].Trim().ToLowerInvariant() : "string";

            switch (t)
            {
                case "datetime":
                case "date": return (name, "global::System.DateTime", false);
                case "int": return (name, "int", false);
                case "double": return (name, "double", false);
                default: return (name, "string", true);
            }
        }

        /// <summary>
        /// 根據 EmitModel 生成對應的 partial class 代碼，並添加到編譯輸出中。
        /// </summary>
        /// <param name="Namespace"></param>
        /// <param name="ClassName"></param>
        /// <param name="BaseFqn"></param>
        /// <param name="SetsCsv"></param>
        /// <param name="AddQty"></param>
        /// <param name="AddCtors"></param>
        /// <param name="Meta"></param>
        /// <returns></returns>
        private sealed record EmitModel(
            string Namespace, string ClassName, string BaseFqn, string SetsCsv,
            bool AddQty, bool AddCtors, string Meta);
    }
}
