using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using OptimFoundation.Internal;

namespace OptimFoundation.Generators
{
    /// <summary>
    /// 編譯時讀取 OptSet、OptParam、OptVar 標記，自動補上資料類別所需的屬性與基底類別。
    /// 在類別上標記 OptSet、OptParam 或 OptVar，再用一個 OptDim&lt;T&gt; 宣告每個維度。
    ///
    ///     [OptSet] + [OptDim&lt;string&gt;("Lot")] → 繼承 SetRowBase 並產生 Lot 屬性（至少一維，否則回報 OPTF008）
    ///     [OptParam] + [OptDim&lt;string&gt;("Lot")] + [OptDim&lt;int&gt;("Op")] → 繼承 ParameterBase，產生維度屬性、QTY 與建構子（不宣告維度時只有一個參數值）
    ///     [OptVar] + [OptDim&lt;DateTime&gt;("Date")] → 繼承 VariableBase 並產生 Date 屬性（也可不宣告維度）
    ///
    /// OptDim 的 T 是該維度的資料型別（string / DateTime / int / long / double / decimal），不能使用 Set 類別作為 T。
    /// 變數型別由類別名前綴決定（VariableB_=Binary / VariableC_=Continuous /
    /// VariableI_=Integer，OPTF001）；
    /// 參數一律含 QTY 值欄位且為最後一個資料屬性；Set 類名須 Set_ 前綴（OPTF003）、Parameter 類名須 Parameter_ 前綴（OPTF002）。
    /// 編譯時會自動產生 OptimFoundation.Modeling 裡的 attribute 定義，使用端加入 using 即可使用。
    /// </summary>
    [Generator]
    public sealed class AutoSetsGenerator : IIncrementalGenerator
    {
        private const string VarAttr = "OptimFoundation.Modeling.OptVarAttribute";
        private const string ParamAttr = "OptimFoundation.Modeling.OptParamAttribute";
        private const string SetAttr = "OptimFoundation.Modeling.OptSetAttribute";

        private const string VariableBaseFqn = "global::OptimFoundation.Core.VariableBase";
        private const string ParameterBaseFqn = "global::OptimFoundation.Core.ParameterBase";
        private const string SetRowBaseFqn = "global::OptimFoundation.Core.SetRowBase";

        private const string TabSpace = "    ";

        // 依類別名前綴判斷變數型別；前綴不合法時回報編譯錯誤，並列出正確命名方式。
        private static readonly DiagnosticDescriptor VarNamingRule = new DiagnosticDescriptor(
            id: "OPTF001",
            title: "OptVar 類別命名不符命名天條",
            messageFormat: "類別 '{0}' 掛 [OptVar]，但名稱無法判定變數型別。命名天條：" + VariablePrefixNaming.NamingGuide + "，例：VariableC_Start",
            category: "OptimFoundation.Naming",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor ParamNamingRule = new DiagnosticDescriptor(
            id: "OPTF002",
            title: "OptParam 類別命名不符命名天條",
            messageFormat: "類別 '{0}' 掛 [OptParam]，但名稱不是 Parameter_ 前綴。命名天條：Parameter_<語意>，例：Parameter_ProcessTime",
            category: "OptimFoundation.Naming",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor SetNamingRule = new DiagnosticDescriptor(
            id: "OPTF003",
            title: "OptSet 類別命名不符命名天條",
            messageFormat: "類別 '{0}' 掛 [OptSet]，但名稱不是 Set_ 前綴。命名天條：Set_<語意>，例：Set_Date",
            category: "OptimFoundation.Naming",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor DimensionTypeRule = new DiagnosticDescriptor(
            id: "OPTF007",
            title: "OptDim 維度型別不受支援",
            messageFormat: "類別 '{0}' 的 [OptDim<{1}>] 型別不受支援；只允許 string / System.DateTime / int / long / double / decimal。",
            category: "OptimFoundation.Naming",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor SetDimensionRequiredRule = new DiagnosticDescriptor(
            id: "OPTF008",
            title: "Set 至少需要一個維度",
            messageFormat: "Set '{0}' 至少必須宣告一個 [OptDim<T>(\"Name\")]；零維只允許 OptParam。",
            category: "OptimFoundation.Naming",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        // 檢查 DataContext 引用的 Set_ / Parameter_ 類別是否漏標 attribute，避免該資料表未註冊而漏掉資料驗證。
        private static readonly DiagnosticDescriptor UnregisteredDataMemberRule = new DiagnosticDescriptor(
            id: "OPTF006",
            title: "DataContext 欄位引用的型別漏掛 attribute，將被靜默排除於資料驗證外",
            messageFormat: "{0}",
            category: "OptimFoundation.DataGuard",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        // 前綴規則與 Core 共用 VariablePrefixNaming；非法前綴回 null（呼叫端報 OPTF001）
        private static string? VarTypeFromPrefix(string className)
        {
            return VariablePrefixNaming.TryResolve(className, out var type)
                ? type
                : null;
        }

        // 編譯時產生的 attribute 定義，使用端不用額外引用定義它們的組件。
        private const string AttributeSource = @"// <auto-generated/>
#nullable enable
using System;

namespace OptimFoundation.Modeling
{
    /// <summary>標記這個類別是一筆 Set row；維度以 OptDim&lt;T&gt; 宣告，至少一個。</summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class OptSetAttribute : Attribute { }

    /// <summary>標記這個類別是一筆 Parameter row；維度以 OptDim&lt;T&gt; 宣告，零到多個，generator 一律補上 QTY。</summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class OptParamAttribute : Attribute { }

    /// <summary>標記這個類別是一支決策變數；維度以 OptDim&lt;T&gt; 宣告，零到多個。變數型別由類別名前綴決定。</summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class OptVarAttribute : Attribute { }

    /// <summary>
    /// 宣告一個維度：T 是該維度的資料型別（string / DateTime / int / long / double / decimal），
    /// name 成為生成的 property 名與 CSV / DB 欄名。宣告順序即 key 組成順序；同一個 Set 用於多個角色時
    /// 各取自己的維度名（例：來源站 From / 目的站 To），可重複標記多次。
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    public sealed class OptDimAttribute<T> : Attribute
    {
        /// <summary>這個維度的名稱。</summary>
        public string Name { get; }

        /// <summary>指定維度名稱。</summary>
        public OptDimAttribute(string name) { Name = name; }
    }
}
";

        /// <summary>
        /// 先用 PostInitialization 產生 attribute 定義，讓使用端可直接引用，
        /// 再分別處理標有 OptSet / OptParam / OptVar 的類別，並為 DataContext 子類別產生資料表註冊程式。
        /// </summary>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
                ctx.AddSource("OptModelingAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            Register(context, VarAttr, ExtractVar);
            Register(context, ParamAttr, ExtractParam);
            Register(context, SetAttr, ExtractSet);

            // 尋找繼承 DataContext 的 partial 類別，為它們產生 RegisterAll；這裡不靠 attribute 判斷。
            var dataContexts = context.SyntaxProvider.CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax cds
                        && cds.Modifiers.Any(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword),
                    transform: static (ctx, _) => ExtractDataContext(ctx))
                .Where(m => m is not null);
            context.RegisterSourceOutput(dataContexts, static (spc, m) => EmitDataContextRegister(spc, m!));
        }

        private static void Register(
            IncrementalGeneratorInitializationContext context,
            string metadataName,
            System.Func<GeneratorAttributeSyntaxContext, EmitModel?> extract)
        {
            var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
                    metadataName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => extract(ctx))
                .Where(m => m is not null);
            context.RegisterSourceOutput(provider, static (spc, m) => Emit(spc, m!));
        }

        // ── 讀取類別與 attribute，整理要產生的成員 ──

        private static EmitModel? ExtractVar(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol symbol) return null;

            string? varType = VarTypeFromPrefix(symbol.Name);
            var (props, badDimType, _) = ResolveDims(symbol);

            return new EmitModel(NamespaceOf(symbol), symbol.Name, VariableBaseFqn,
                AddQty: false, AddCtors: false,
                Meta: varType == null ? string.Empty : $"VarType={varType}（由類別名前綴決定）",
                NamingViolation: varType == null ? VarNamingRule : (badDimType == null ? null : DimensionTypeRule),
                DiagLocation: symbol.Locations.FirstOrDefault(),
                Props: props, DiagArg: badDimType ?? symbol.Name);
        }

        private static EmitModel? ExtractParam(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol symbol) return null;

            bool badPrefix = !symbol.Name.StartsWith("Parameter_", System.StringComparison.Ordinal);
            var (props, badDimType, _) = ResolveDims(symbol);

            return new EmitModel(NamespaceOf(symbol), symbol.Name, ParameterBaseFqn,
                AddQty: true, AddCtors: true, Meta: string.Empty,
                NamingViolation: badPrefix ? ParamNamingRule : (badDimType == null ? null : DimensionTypeRule),
                DiagLocation: symbol.Locations.FirstOrDefault(),
                Props: props, DiagArg: badDimType ?? symbol.Name);
        }

        private static EmitModel? ExtractSet(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol symbol) return null;

            bool badPrefix = !symbol.Name.StartsWith("Set_", System.StringComparison.Ordinal);
            var (props, badDimType, hasDims) = ResolveDims(symbol);

            DiagnosticDescriptor? diag = badPrefix ? SetNamingRule
                : !hasDims ? SetDimensionRequiredRule
                : badDimType == null ? null : DimensionTypeRule;

            return new EmitModel(NamespaceOf(symbol), symbol.Name, SetRowBaseFqn,
                AddQty: false, AddCtors: false, Meta: string.Empty,
                NamingViolation: diag, DiagLocation: symbol.Locations.FirstOrDefault(),
                Props: props, DiagArg: badDimType ?? symbol.Name);
        }

        // ── 找出 DataContext 需要註冊的資料表 ──
        // 檢查類別是否繼承 DataContext，再產生它的 RegisterAll override。

        private static DataContextEmitModel? ExtractDataContext(GeneratorSyntaxContext ctx)
        {
            var cds = (ClassDeclarationSyntax)ctx.Node;
            if (ctx.SemanticModel.GetDeclaredSymbol(cds) is not INamedTypeSymbol symbol) return null;
            if (!DerivesFrom(symbol, "OptimFoundation.Core.DataContext")) return null;

            // 同一類別有多份 partial 宣告時只處理第一份，避免重複產生 RegisterAll；GetMembers() 已包含各份宣告的成員。
            var syntaxRefs = symbol.DeclaringSyntaxReferences;
            if (syntaxRefs.Length > 1)
            {
                var first = syntaxRefs
                    .OrderBy(r => r.SyntaxTree.FilePath, System.StringComparer.Ordinal)
                    .ThenBy(r => r.Span.Start)
                    .First();
                if (first.SyntaxTree != cds.SyntaxTree || first.Span != cds.Span) return null;
            }

            var sets = new System.Collections.Generic.List<SetReg>();
            var parms = new System.Collections.Generic.List<ParamReg>();
            var diagnostics = new System.Collections.Generic.List<Diagnostic>();

            foreach (var member in symbol.GetMembers())
            {
                ITypeSymbol? memberType = member switch
                {
                    IFieldSymbol f when !f.IsStatic && f.DeclaredAccessibility == Accessibility.Public => f.Type,
                    IPropertySymbol p when !p.IsStatic && p.DeclaredAccessibility == Accessibility.Public => p.Type,
                    _ => null
                };
                if (memberType is not INamedTypeSymbol namedType) continue;

                // 單一 Set 物件不是資料表；只註冊 List<T> / IReadOnlyList<T> 集合。
                if (HasOptSetAttribute(namedType)) continue;

                if (IsListLike(namedType, out var setType) && HasOptSetAttribute(setType))
                {
                    sets.Add(new SetReg(member.Name, ResolveIndexNames(setType)));
                    continue;
                }

                if (TryGetParamElementType(namedType, out var paramType))
                {
                    string[] indexProps = ResolveIndexNames(paramType);
                    string[] numberProps = ResolveNumberPropNames(paramType);
                    parms.Add(new ParamReg(member.Name, indexProps, numberProps));
                    continue;
                }

                // 型別名稱以 Set_ / Parameter_ 開頭卻漏標 attribute 時，前面的 HasOptSetAttribute /
                // TryGetParamElementType 會略過它；這裡回報 OPTF006，避免資料未註冊卻仍通過編譯。
                if (namedType.Name.StartsWith("Set_", System.StringComparison.Ordinal))
                {
                    diagnostics.Add(Diagnostic.Create(UnregisteredDataMemberRule, member.Locations.FirstOrDefault(),
                        $"'{namedType.Name}' 被 '{symbol.Name}.{member.Name}' 引用但未掛 [OptSet]，將無法納入資料驗證；請補上 attribute"));
                    continue;
                }

                if (IsListLike(namedType, out var elem))
                {
                    if (elem.Name.StartsWith("Parameter_", System.StringComparison.Ordinal))
                        diagnostics.Add(Diagnostic.Create(UnregisteredDataMemberRule, member.Locations.FirstOrDefault(),
                            $"'{elem.Name}' 被 '{symbol.Name}.{member.Name}' 引用但未掛 [OptParam]，將無法納入資料驗證；請補上 attribute"));
                    else if (elem.Name.StartsWith("Set_", System.StringComparison.Ordinal) && !HasOptSetAttribute(elem))
                        diagnostics.Add(Diagnostic.Create(UnregisteredDataMemberRule, member.Locations.FirstOrDefault(),
                            $"'{elem.Name}' 被 '{symbol.Name}.{member.Name}' 引用但未掛 [OptSet]，將無法納入資料驗證；請補上 attribute"));
                }
            }

            return new DataContextEmitModel(
                NamespaceOf(symbol), symbol.Name, sets.ToArray(), parms.ToArray(), diagnostics.ToArray());
        }

        private static bool HasOptSetAttribute(INamedTypeSymbol t)
            => t.GetAttributes().Any(a => a.AttributeClass != null && a.AttributeClass.Name == "OptSetAttribute");

        private static bool HasOptParamAttribute(INamedTypeSymbol t)
            => t.GetAttributes().Any(a => a.AttributeClass != null && a.AttributeClass.Name == "OptParamAttribute");

        // 取出 List<T> / IReadOnlyList<T> 的元素型別 T；這裡只檢查集合型別，不檢查 T 是否標有 OptParam。
        private static bool IsListLike(INamedTypeSymbol listType, out INamedTypeSymbol elementType)
        {
            elementType = null!;
            if (!listType.IsGenericType || listType.TypeArguments.Length != 1) return false;

            string originalName = listType.OriginalDefinition.ToDisplayString();
            bool isListLike = originalName == "System.Collections.Generic.List<T>"
                || originalName == "System.Collections.Generic.IReadOnlyList<T>";
            if (!isListLike) return false;

            if (listType.TypeArguments[0] is not INamedTypeSymbol elem) return false;
            elementType = elem;
            return true;
        }

        // 取出 List<T> / IReadOnlyList<T> 的元素型別，且要求 T 標有 OptParam。
        private static bool TryGetParamElementType(INamedTypeSymbol listType, out INamedTypeSymbol elementType)
        {
            elementType = null!;
            if (!IsListLike(listType, out var elem)) return false;
            if (!HasOptParamAttribute(elem)) return false;

            elementType = elem;
            return true;
        }

        private static bool DerivesFrom(INamedTypeSymbol type, string fullyQualifiedBaseName)
        {
            for (var b = type.BaseType; b != null; b = b.BaseType)
                if (b.ToDisplayString() == fullyQualifiedBaseName) return true;
            return false;
        }

        // 索引欄位直接取自 OptDim 宣告，與產生 Parameter 屬性時使用相同規則，不依名稱猜測。
        // 這份規則同時用於註冊索引欄位名稱，以及找出需要數值檢查的欄位。
        private static string[] ResolveIndexNames(INamedTypeSymbol paramType)
            => ResolveDims(paramType).props.Select(p => p.Name).ToArray();

        // 找出 Parameter 所有需要數值檢查的 double 屬性名稱，依下列順序加入並排除重複：
        // 1) OptDim 宣告為 double 的維度；屬性尚未產生，所以從 attribute 讀取。
        // 2) 一定會產生的 QTY；目前同樣還無法從型別成員中讀到。
        // 3) 使用者在 partial 類別手寫的 public double 屬性；用 GetMembers() 取得。
        // 不能只檢查 QTY，否則會漏掉使用者自行宣告的數值欄位。
        // 例如 Profit、Required、Stock 等 double 欄位也要檢查；模型係數仍統一存放在 QTY。
        // int、decimal 等非 double 欄位不列入這項數值檢查。
        private static string[] ResolveNumberPropNames(INamedTypeSymbol paramType)
        {
            var names = new System.Collections.Generic.List<string>();
            var seen = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal);

            foreach (var p in ResolveDims(paramType).props.Where(p => p.Type == "double"))
                if (seen.Add(p.Name)) names.Add(p.Name);

            if (seen.Add("QTY"))
                names.Add("QTY");

            foreach (var member in paramType.GetMembers())
            {
                if (member is not IPropertySymbol prop) continue;
                if (prop.IsStatic || prop.DeclaredAccessibility != Accessibility.Public) continue;
                if (prop.Type.SpecialType != SpecialType.System_Double) continue;
                if (seen.Add(prop.Name)) names.Add(prop.Name);
            }

            return names.ToArray();
        }

        private static void EmitDataContextRegister(SourceProductionContext spc, DataContextEmitModel m)
        {
            foreach (var d in m.Diagnostics)
                spc.ReportDiagnostic(d);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNs = m.Namespace.Length > 0;
            if (hasNs)
            {
                sb.Append("namespace ").Append(m.Namespace).AppendLine();
                sb.AppendLine("{");
            }

            sb.Append("    public partial class ").Append(m.ClassName).AppendLine();
            sb.AppendLine("    {");
            sb.AppendLine("        // 由 AutoSetsGenerator 依 DataContext 繼承關係產生（見框架資料防護規格）");
            sb.AppendLine("        protected override void RegisterAll()");
            sb.AppendLine("        {");

            foreach (var s in m.Sets)
            {
                string idxArr = "new[] { " + string.Join(", ", s.IndexNames.Select(n => "\"" + n + "\"")) + " }";
                string indexOf = "r => new object[] { " + string.Join(", ", s.IndexNames.Select(n => "r." + n)) + " }";

                sb.Append("            RegisterSet(").Append(s.FieldName).Append(", ").Append(idxArr)
                  .Append(", ").Append(indexOf)
                  .AppendLine(");");
            }

            foreach (var p in m.Params)
            {
                string idxArr = p.IndexNames.Length == 0
                    ? "global::System.Array.Empty<string>()"
                    : "new[] { " + string.Join(", ", p.IndexNames.Select(n => "\"" + n + "\"")) + " }";
                string indexOf = p.IndexNames.Length == 0
                    ? "r => global::System.Array.Empty<object>()"
                    : "r => new object[] { " + string.Join(", ", p.IndexNames.Select(n => "r." + n)) + " }";
                string numbersOf = p.NumberProps.Length == 0
                    ? "r => global::System.Array.Empty<(string, double)>()"
                    : "r => new (string, double)[] { " + string.Join(", ", p.NumberProps.Select(n => "(\"" + n + "\", r." + n + ")")) + " }";

                sb.Append("            RegisterParam(").Append(p.FieldName).Append(", ").Append(idxArr)
                  .Append(", ").Append(indexOf).Append(", ").Append(numbersOf)
                  .AppendLine(");");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            if (hasNs) sb.AppendLine("}");

            spc.AddSource($"{m.ClassName}.DataContextRegister.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        // 依宣告順序讀取類別上的 OptDim<T>("name")，整理每個待產生屬性的名稱與型別。
        // 回傳 (props, 不合法的維度型別顯示名或 null, 有沒有宣告維度)
        private static (PropSpec[] props, string? badDimType, bool has) ResolveDims(INamedTypeSymbol symbol)
        {
            var dims = symbol.GetAttributes()
                .Where(a => a.AttributeClass != null && a.AttributeClass.Name == "OptDimAttribute" && a.AttributeClass.IsGenericType)
                .ToList();
            if (dims.Count == 0) return (System.Array.Empty<PropSpec>(), null, false);

            var list = new System.Collections.Generic.List<PropSpec>();
            string? badDimType = null;
            foreach (var d in dims)
            {
                string name = d.ConstructorArguments.Length > 0 ? d.ConstructorArguments[0].Value?.ToString() ?? string.Empty : string.Empty;
                var type = d.AttributeClass!.TypeArguments.Length == 1 ? d.AttributeClass.TypeArguments[0] : null;
                if (type == null)
                {
                    badDimType ??= "?";
                    list.Add(new PropSpec(name, "string", true));
                    continue;
                }
                var (fq, isStr, legal) = MapElem(type);
                if (!legal) badDimType ??= type.ToDisplayString();
                list.Add(new PropSpec(name, fq, isStr));
            }
            return (list.ToArray(), badDimType, true);
        }

        // 將 CLR 型別轉成產碼用的 C# 型別名稱，並回傳它是否為 string、是否受支援。
        private static (string fq, bool isString, bool legal) MapElem(ITypeSymbol t)
        {
            switch (t.SpecialType)
            {
                case SpecialType.System_String: return ("string", true, true);
                case SpecialType.System_Int32: return ("int", false, true);
                case SpecialType.System_Int64: return ("long", false, true);
                case SpecialType.System_Double: return ("double", false, true);
                case SpecialType.System_Decimal: return ("decimal", false, true);
                case SpecialType.System_DateTime: return ("global::System.DateTime", false, true);
            }
            if (t.ToDisplayString() == "System.DateTime") return ("global::System.DateTime", false, true);
            return ("string", true, false);
        }

        private static string NamespaceOf(INamedTypeSymbol s)
            => s.ContainingNamespace.IsGlobalNamespace ? string.Empty : s.ContainingNamespace.ToDisplayString();

        private static void Emit(SourceProductionContext spc, EmitModel m)
        {
            if (m.NamingViolation != null)
            {
                spc.ReportDiagnostic(m.NamingViolation == DimensionTypeRule
                    ? Diagnostic.Create(m.NamingViolation, m.DiagLocation, m.ClassName, m.DiagArg ?? m.ClassName)
                    : Diagnostic.Create(m.NamingViolation, m.DiagLocation, m.ClassName));
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNs = m.Namespace.Length > 0;
            if (hasNs)
            {
                sb.Append("namespace ").Append(m.Namespace).AppendLine();
                sb.AppendLine("{");
            }

            if (m.Meta.Length > 0)
                sb.Append("    // [").Append(m.Meta).AppendLine("]：由 AutoSetsGenerator 產生");
            sb.Append("    public partial class ").Append(m.ClassName).Append(" : ").AppendLine(m.BaseFqn);
            sb.AppendLine("    {");

            foreach (var p in m.Props)
            {
                if (p.IsString)
                    sb.Append("        public string ").Append(p.Name).AppendLine(" { get; set; } = string.Empty;");
                else
                    sb.Append("        public ").Append(p.Type).Append(' ').Append(p.Name).AppendLine(" { get; set; }");
            }

            if (m.AddQty)
                sb.AppendLine("        public double QTY { get; set; }");

            // 只有一個維度的 Set 可隱含轉型成該維度的值，方便在建模迴圈中使用。
            // 多維度的 Set 則產生 Deconstruct，讓呼叫端用 C# 解構語法取出各維度值。
            if (m.BaseFqn == SetRowBaseFqn)
            {
                if (m.Props.Length == 1)
                {
                    sb.AppendLine();
                    sb.Append("        public static implicit operator ").Append(m.Props[0].Type)
                      .Append('(').Append(m.ClassName).Append(" row) => row.")
                      .Append(m.Props[0].Name).AppendLine(";");
                }
                else if (m.Props.Length > 1)
                {
                    sb.AppendLine();
                    sb.Append("        public void Deconstruct(");
                    sb.Append(string.Join(", ", m.Props.Select(p => "out " + p.Type + " " + p.Name)));
                    sb.AppendLine(")");
                    sb.AppendLine("        {");
                    foreach (var p in m.Props)
                        sb.Append("            ").Append(p.Name).Append(" = this.").Append(p.Name).AppendLine(";");
                    sb.AppendLine("        }");
                }
            }

            if (m.AddCtors)
            {
                sb.AppendLine();
                sb.Append("        public ").Append(m.ClassName).AppendLine("(params object[] sets) => InitClassBySets(sets);");
                sb.Append("        public ").Append(m.ClassName).AppendLine("() { }");
            }

            sb.AppendLine("    }");
            if (hasNs) sb.AppendLine("}");

            spc.AddSource($"{m.ClassName}.AutoSets.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private sealed record PropSpec(string Name, string Type, bool IsString);

        private sealed record EmitModel(
            string Namespace, string ClassName, string BaseFqn,
            bool AddQty, bool AddCtors, string Meta,
            DiagnosticDescriptor? NamingViolation, Location? DiagLocation,
            PropSpec[] Props, string? DiagArg);

        private sealed record SetReg(string FieldName, string[] IndexNames);
        private sealed record ParamReg(string FieldName, string[] IndexNames, string[] NumberProps);
        private sealed record DataContextEmitModel(
            string Namespace, string ClassName, SetReg[] Sets, ParamReg[] Params, Diagnostic[] Diagnostics);
    }
}
