using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace OptimFoundation.Generators
{
    /// <summary>
    /// AutoSets source generator。編譯期把宣告式標記補成完整 class。兩條並存路徑（後者為 2026-07 新增，前者原封保留為逃生口）：
    ///
    /// A. 字串式（逃生口 / 遷移用）：
    ///     [OptVar("Date:DateTime", "Employee")]     → VariableBase + 依序 set 屬性
    ///     [OptParam("Date:DateTime", "Group")]      → ParameterBase + set 屬性 + QTY + ctor
    ///
    /// B. Set 積木 + 泛型引用（paved path）：
    ///     [OptSet&lt;DateTime&gt;] partial class Set_Date {}   → SetBase&lt;DateTime&gt;
    ///     [OptSet]               partial class Set_Emp {}    → SetBase&lt;string&gt;（無參數 = 預設 string）
    ///     [OptVar&lt;Set_Date, Set_Emp&gt;]                     → VariableBase，property 名/型別從積木自動抓
    ///     [OptParam&lt;Set_Date, Set_Grp&gt;]                   → ParameterBase + QTY + ctor
    ///   泛型 attribute 以 where T : ISetBrick 約束，引用非積木 = CS0311 原生 compile error。
    ///
    /// 兩路共同：變數型別由類別名前綴決定（VariableB_=Binary / VariableX_=Continuous / VariableI_=Integer，OPTF001）；
    /// 參數一律含 QTY 值欄位且為最後一個資料屬性；Set 積木類名須 Set_ 前綴（OPTF003）。
    /// attribute / marker 由本 generator 於編譯期注入 OptimFoundation.Modeling namespace，使用端只需 using 該 namespace。
    /// </summary>
    [Generator]
    public sealed class AutoSetsGenerator : IIncrementalGenerator
    {
        private const string VarAttr = "OptimFoundation.Modeling.OptVarAttribute";
        private const string ParamAttr = "OptimFoundation.Modeling.OptParamAttribute";
        private const string SetAttr = "OptimFoundation.Modeling.OptSetAttribute";

        private const string VariableBaseFqn = "global::OptimFoundation.Core.VariableBase";
        private const string ParameterBaseFqn = "global::OptimFoundation.Core.ParameterBase";
        private const string SetBaseFqn = "global::OptimFoundation.Core.SetBase";

        private const int MaxArity = 6;

        // 命名天條：型別由類別名前綴決定，前綴不合法直接 compile error，訊息教正確取名
        private static readonly DiagnosticDescriptor VarNamingRule = new DiagnosticDescriptor(
            id: "OPTF001",
            title: "OptVar 類別命名不符命名天條",
            messageFormat: "類別 '{0}' 掛 [OptVar]，但名稱無法判定變數型別。命名天條：VariableB_<語意>（Binary）/ VariableX_<語意>（Continuous）/ VariableI_<語意>（Integer），例：VariableX_Start",
            category: "OptimFoundation.Naming",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor ParamNamingRule = new DiagnosticDescriptor(
            id: "OPTF002",
            title: "OptParam 類別命名不符命名天條",
            messageFormat: "類別 '{0}' 掛 [OptParam]，但名稱不是 Parameter_ 前綴。命名天條：Parameter_<語意>，例：Parameter_ProcessTime",
            category: "OptimFoundation.Naming",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor SetNamingRule = new DiagnosticDescriptor(
            id: "OPTF003",
            title: "OptSet 類別命名不符命名天條",
            messageFormat: "類別 '{0}' 掛 [OptSet]，但名稱不是 Set_ 前綴。命名天條：Set_<語意>，例：Set_Date",
            category: "OptimFoundation.Naming",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor SetElementTypeRule = new DiagnosticDescriptor(
            id: "OPTF004",
            title: "OptSet 元素型別不在合法域",
            messageFormat: "[OptSet<{1}>]（類別 '{0}'）的元素型別不受支援。合法：string / System.DateTime / int / long / double / decimal。",
            category: "OptimFoundation.Naming",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor NotASetBrickRule = new DiagnosticDescriptor(
            id: "OPTF005",
            title: "泛型引用的型別不是 Set 積木",
            messageFormat: "類別 '{0}' 的維度引用了 '{1}'，但它沒有掛 [OptSet]／[OptSet<T>]，不是合法 Set 積木。",
            category: "OptimFoundation.Naming",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        // "VariableB_Assign" → "Binary"；非法前綴回 null（呼叫端報 OPTF001）
        private static string? VarTypeFromPrefix(string className)
        {
            if (className.StartsWith("VariableB_", System.StringComparison.Ordinal)) return "Binary";
            if (className.StartsWith("VariableX_", System.StringComparison.Ordinal)) return "Continuous";
            if (className.StartsWith("VariableI_", System.StringComparison.Ordinal)) return "Integer";
            return null;
        }

        // 注入到使用端編譯的 attribute + marker（使用端不需任何額外組件）。
        // 字串式 OptVar/OptParam 原封保留（逃生口）；新增 OptSet 與泛型 OptVar/OptParam（arity 1..6）。
        private static readonly string AttributeSource = BuildAttributeSource();

        private static string BuildAttributeSource()
        {
            var sb = new StringBuilder();
            sb.Append(@"// <auto-generated/>
#nullable enable
using System;

namespace OptimFoundation.Modeling
{
    // ── 字串式（逃生口 / 遷移用），原封保留 ──
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class OptVarAttribute : Attribute
    {
        public string[] Sets { get; }
        public OptVarAttribute(params string[] sets) { Sets = sets; }
    }

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class OptParamAttribute : Attribute
    {
        public string[] Sets { get; }
        /// <summary>true（預設）會生成 QTY 值欄位；純 key 參數設 false。</summary>
        public bool HasValue { get; set; } = true;
        public OptParamAttribute(params string[] sets) { Sets = sets; }
    }

    // ── Set 積木：元素型別由泛型參數帶（無參數 = 預設 string） ──
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class OptSetAttribute : Attribute { }

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class OptSetAttribute<T> : Attribute { }

    // ── 具名維度：同 set 多維度 / 自訂 index 名。泛型 = 來源 set（直接綁，不 alias），字串 = 維度名 ──
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    public sealed class OptDimAttribute<TSet> : Attribute where TSet : global::OptimFoundation.Core.ISetBrick
    {
        public string Name { get; }
        public OptDimAttribute(string name) { Name = name; }
    }

");
            // 泛型 OptVar / OptParam：arity 1..MaxArity，where Tn : ISetBrick → 引用非積木 = CS0311
            for (int n = 1; n <= MaxArity; n++)
            {
                string tparams = string.Join(", ", Enumerable.Range(1, n).Select(i => "T" + i));
                string constraints = string.Join(" ", Enumerable.Range(1, n)
                    .Select(i => $"where T{i} : global::OptimFoundation.Core.ISetBrick"));

                sb.Append($@"    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class OptVarAttribute<{tparams}> : Attribute {constraints} {{ }}

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class OptParamAttribute<{tparams}> : Attribute {constraints}
    {{
        /// <summary>true（預設）會生成 QTY 值欄位；純 key 參數設 false。</summary>
        public bool HasValue {{ get; set; }} = true;
    }}

");
            }
            sb.Append("}\n");
            return sb.ToString();
        }

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
                ctx.AddSource("OptModelingAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            // A. 字串式（原封保留）
            Register(context, VarAttr, ExtractVar);
            Register(context, ParamAttr, ExtractParam);

            // B. Set 積木（非泛型預設 string + 泛型 arity 1）
            Register(context, SetAttr, ExtractSet);
            Register(context, SetAttr + "`1", ExtractSet);

            // B. 泛型 Var / Param（arity 1..MaxArity）
            for (int n = 1; n <= MaxArity; n++)
            {
                Register(context, VarAttr + "`" + n, ExtractVarGeneric);
                Register(context, ParamAttr + "`" + n, ExtractParamGeneric);
            }
        }

        private static void Register(
            IncrementalGeneratorInitializationContext context,
            string metadataName,
            System.Func<GeneratorAttributeSyntaxContext, EmitModel?> extract)
        {
            var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
                    metadataName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => extract(ctx))
                .Where(m => m is not null);
            context.RegisterSourceOutput(provider, static (spc, m) => Emit(spc, m!));
        }

        // ── A. 字串式提取（原封保留） ──

        private static EmitModel? ExtractVar(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol symbol || ctx.Attributes.Length == 0) return null;

            string? varType = VarTypeFromPrefix(symbol.Name);

            // 具名維度 [OptDim<TSet>("name")] 優先（同 set 多維度 / 自訂 index 名）
            var (dimProps, dimNotBrick, hasDims) = ResolveDims(symbol);
            if (hasDims)
                return new EmitModel(NamespaceOf(symbol), symbol.Name, VariableBaseFqn, string.Empty,
                    AddQty: false, AddCtors: false,
                    Meta: varType == null ? string.Empty : $"VarType={varType}（由類別名前綴決定）",
                    NamingViolation: varType == null ? VarNamingRule : dimNotBrick,
                    DiagLocation: symbol.Locations.FirstOrDefault(),
                    Props: dimProps, DiagArg: symbol.Name);

            // 字串式（原封保留）
            var args = ctx.Attributes[0].ConstructorArguments;
            if (args.Length < 1) return null;

            string setsCsv = JoinSets(args[0]);

            return new EmitModel(NamespaceOf(symbol), symbol.Name, VariableBaseFqn, setsCsv,
                AddQty: false, AddCtors: false,
                Meta: varType == null ? string.Empty : $"VarType={varType}（由類別名前綴決定）",
                NamingViolation: varType == null ? VarNamingRule : null,
                DiagLocation: symbol.Locations.FirstOrDefault());
        }

        private static EmitModel? ExtractParam(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol symbol || ctx.Attributes.Length == 0) return null;

            var attr = ctx.Attributes[0];
            bool hasValue = ReadHasValue(attr);
            bool badPrefix = !symbol.Name.StartsWith("Parameter_", System.StringComparison.Ordinal);

            // 具名維度 [OptDim<TSet>("name")] 優先
            var (dimProps, dimNotBrick, hasDims) = ResolveDims(symbol);
            if (hasDims)
                return new EmitModel(NamespaceOf(symbol), symbol.Name, ParameterBaseFqn, string.Empty,
                    AddQty: hasValue, AddCtors: true, Meta: string.Empty,
                    NamingViolation: badPrefix ? ParamNamingRule : dimNotBrick,
                    DiagLocation: symbol.Locations.FirstOrDefault(),
                    Props: dimProps, DiagArg: symbol.Name);

            // 字串式（原封保留）
            if (attr.ConstructorArguments.Length < 1) return null;

            string setsCsv = JoinSets(attr.ConstructorArguments[0]);

            return new EmitModel(NamespaceOf(symbol), symbol.Name, ParameterBaseFqn, setsCsv,
                AddQty: hasValue, AddCtors: true, Meta: string.Empty,
                NamingViolation: badPrefix ? ParamNamingRule : null,
                DiagLocation: symbol.Locations.FirstOrDefault());
        }

        // ── B. Set 積木 + 泛型引用提取（新增） ──

        private static EmitModel? ExtractSet(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol symbol || ctx.Attributes.Length == 0) return null;

            var loc = symbol.Locations.FirstOrDefault();
            bool badPrefix = !symbol.Name.StartsWith("Set_", System.StringComparison.Ordinal);

            // 元素型別：泛型 [OptSet<T>] 取型別參數；非泛型 [OptSet] 預設 string
            var attrClass = ctx.Attributes[0].AttributeClass;
            string elemFq = "string";
            string elemDisplay = "string";
            bool legal = true;
            if (attrClass != null && attrClass.IsGenericType && attrClass.TypeArguments.Length == 1)
            {
                var (fq, _, ok) = MapElem(attrClass.TypeArguments[0]);
                elemFq = fq;
                elemDisplay = attrClass.TypeArguments[0].ToDisplayString();
                legal = ok;
            }

            var diag = badPrefix ? SetNamingRule : (legal ? null : SetElementTypeRule);

            return new EmitModel(NamespaceOf(symbol), symbol.Name, $"{SetBaseFqn}<{elemFq}>", string.Empty,
                AddQty: false, AddCtors: false, Meta: string.Empty,
                NamingViolation: diag, DiagLocation: loc,
                Props: System.Array.Empty<PropSpec>(), DiagArg: elemDisplay);
        }

        private static EmitModel? ExtractVarGeneric(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol symbol || ctx.Attributes.Length == 0) return null;

            string? varType = VarTypeFromPrefix(symbol.Name);
            var (props, notBrick) = ResolveBricks(ctx.Attributes[0].AttributeClass);

            return new EmitModel(NamespaceOf(symbol), symbol.Name, VariableBaseFqn, string.Empty,
                AddQty: false, AddCtors: false,
                Meta: varType == null ? string.Empty : $"VarType={varType}（由類別名前綴決定）",
                NamingViolation: varType == null ? VarNamingRule : notBrick,
                DiagLocation: symbol.Locations.FirstOrDefault(),
                Props: props, DiagArg: symbol.Name);
        }

        private static EmitModel? ExtractParamGeneric(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol symbol || ctx.Attributes.Length == 0) return null;

            bool hasValue = ReadHasValue(ctx.Attributes[0]);
            bool badPrefix = !symbol.Name.StartsWith("Parameter_", System.StringComparison.Ordinal);
            var (props, notBrick) = ResolveBricks(ctx.Attributes[0].AttributeClass);

            return new EmitModel(NamespaceOf(symbol), symbol.Name, ParameterBaseFqn, string.Empty,
                AddQty: hasValue, AddCtors: true, Meta: string.Empty,
                NamingViolation: badPrefix ? ParamNamingRule : notBrick,
                DiagLocation: symbol.Locations.FirstOrDefault(),
                Props: props, DiagArg: symbol.Name);
        }

        // 把泛型 attribute 的型別參數（Set 積木）解析成 property 規格。回傳 (props, 若有非積木則帶 diagnostic)
        private static (PropSpec[] props, DiagnosticDescriptor? notBrick) ResolveBricks(INamedTypeSymbol? attrClass)
        {
            if (attrClass == null || attrClass.TypeArguments.Length == 0)
                return (System.Array.Empty<PropSpec>(), null);

            var list = new System.Collections.Generic.List<PropSpec>();
            DiagnosticDescriptor? notBrick = null;

            foreach (var arg in attrClass.TypeArguments)
            {
                string propName = arg.Name.StartsWith("Set_", System.StringComparison.Ordinal)
                    ? arg.Name.Substring(4) : arg.Name;

                var optSet = arg.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass != null && a.AttributeClass.Name == "OptSetAttribute");

                if (optSet == null)
                {
                    notBrick = NotASetBrickRule;
                    list.Add(new PropSpec(propName, "string", true));
                    continue;
                }

                if (optSet.AttributeClass!.IsGenericType && optSet.AttributeClass.TypeArguments.Length == 1)
                {
                    var (fq, isStr, _) = MapElem(optSet.AttributeClass.TypeArguments[0]);
                    list.Add(new PropSpec(propName, fq, isStr));
                }
                else
                {
                    list.Add(new PropSpec(propName, "string", true));
                }
            }
            return (list.ToArray(), notBrick);
        }

        // 讀 class 上所有 [OptDim<TSet>("name")]（宣告序）→ property 規格。名字=arg、型別=TSet 的 [OptSet<T>]
        private static (PropSpec[] props, DiagnosticDescriptor? notBrick, bool has) ResolveDims(INamedTypeSymbol symbol)
        {
            var dims = symbol.GetAttributes()
                .Where(a => a.AttributeClass != null && a.AttributeClass.Name == "OptDimAttribute" && a.AttributeClass.IsGenericType)
                .ToList();
            if (dims.Count == 0) return (System.Array.Empty<PropSpec>(), null, false);

            var list = new System.Collections.Generic.List<PropSpec>();
            DiagnosticDescriptor? notBrick = null;
            foreach (var d in dims)
            {
                string name = d.ConstructorArguments.Length > 0 ? d.ConstructorArguments[0].Value?.ToString() ?? string.Empty : string.Empty;
                var setSym = d.AttributeClass!.TypeArguments.Length == 1 ? d.AttributeClass.TypeArguments[0] : null;
                var optSet = setSym?.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "OptSetAttribute");
                if (optSet == null)
                {
                    notBrick = NotASetBrickRule;
                    list.Add(new PropSpec(name, "string", true));
                    continue;
                }
                var (fq, isStr) = ElemFromOptSetAttr(optSet.AttributeClass!);
                list.Add(new PropSpec(name, fq, isStr));
            }
            return (list.ToArray(), notBrick, true);
        }

        // OptSetAttribute（generic 或非 generic）→ 元素型別
        private static (string fq, bool isString) ElemFromOptSetAttr(INamedTypeSymbol optSetAttrClass)
        {
            if (optSetAttrClass.IsGenericType && optSetAttrClass.TypeArguments.Length == 1)
            {
                var (fq, isStr, _) = MapElem(optSetAttrClass.TypeArguments[0]);
                return (fq, isStr);
            }
            return ("string", true);
        }

        // CLR 元素型別 → (生成用 fq 型別, 是否 string, 是否合法域)
        private static (string fq, bool isString, bool legal) MapElem(ITypeSymbol t)
        {
            switch (t.SpecialType)
            {
                case SpecialType.System_String: return ("string", true, true);
                case SpecialType.System_Int32: return ("int", false, true);
                case SpecialType.System_Int64: return ("long", false, true);
                case SpecialType.System_Double: return ("double", false, true);
                case SpecialType.System_Decimal: return ("decimal", false, true);
                case SpecialType.System_DateTime: return ("global::System.DateTime", false, true);
            }
            if (t.ToDisplayString() == "System.DateTime") return ("global::System.DateTime", false, true);
            return ("string", true, false);
        }

        private static bool ReadHasValue(AttributeData attr)
        {
            foreach (var na in attr.NamedArguments)
                if (na.Key == "HasValue" && na.Value.Value is bool b) return b;
            return true;
        }

        private static string JoinSets(TypedConstant arg)
        {
            if (arg.Kind != TypedConstantKind.Array) return string.Empty;
            var sets = arg.Values.Select(v => v.Value?.ToString() ?? string.Empty).Where(s => s.Length > 0);
            return string.Join("|", sets);
        }

        private static string NamespaceOf(INamedTypeSymbol s)
            => s.ContainingNamespace.IsGlobalNamespace ? string.Empty : s.ContainingNamespace.ToDisplayString();

        private static void Emit(SourceProductionContext spc, EmitModel m)
        {
            if (m.NamingViolation != null)
            {
                string arg = m.DiagArg ?? m.ClassName;
                spc.ReportDiagnostic(m.NamingViolation == SetElementTypeRule || m.NamingViolation == NotASetBrickRule
                    ? Diagnostic.Create(m.NamingViolation, m.DiagLocation, m.ClassName, arg)
                    : Diagnostic.Create(m.NamingViolation, m.DiagLocation, m.ClassName));
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNs = m.Namespace.Length > 0;
            if (hasNs)
            {
                sb.Append("namespace ").Append(m.Namespace).AppendLine();
                sb.AppendLine("{");
            }

            if (m.Meta.Length > 0)
                sb.Append("    // [").Append(m.Meta).AppendLine("] —— 由 AutoSetsGenerator 生成");
            sb.Append("    public partial class ").Append(m.ClassName).Append(" : ").AppendLine(m.BaseFqn);
            sb.AppendLine("    {");

            // 屬性：泛型路徑用預解析的 Props；字串路徑用 SetsCsv + ParseSet（原邏輯）
            if (m.Props != null)
            {
                foreach (var p in m.Props)
                {
                    if (p.IsString)
                        sb.Append("        public string ").Append(p.Name).AppendLine(" { get; set; } = string.Empty;");
                    else
                        sb.Append("        public ").Append(p.Type).Append(' ').Append(p.Name).AppendLine(" { get; set; }");
                }
            }
            else
            {
                string[] sets = m.SetsCsv.Length == 0 ? System.Array.Empty<string>() : m.SetsCsv.Split('|');
                foreach (var raw in sets)
                {
                    var (name, type, isString) = ParseSet(raw);
                    if (isString)
                        sb.Append("        public string ").Append(name).AppendLine(" { get; set; } = string.Empty;");
                    else
                        sb.Append("        public ").Append(type).Append(' ').Append(name).AppendLine(" { get; set; }");
                }
            }

            if (m.AddQty)
                sb.AppendLine("        public double QTY { get; set; }");

            if (m.AddCtors)
            {
                sb.AppendLine();
                sb.Append("        public ").Append(m.ClassName).AppendLine("(params object[] sets) => InitClassBySets(sets);");
                sb.Append("        public ").Append(m.ClassName).AppendLine("() { }");
            }

            sb.AppendLine("    }");
            if (hasNs) sb.AppendLine("}");

            spc.AddSource($"{m.ClassName}.AutoSets.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        // "Name" → string；"Name:DateTime|date|int|double" → 對應型別（字串路徑用）
        private static (string name, string type, bool isString) ParseSet(string raw)
        {
            var parts = raw.Split(':');
            string name = parts[0].Trim();
            string t = parts.Length > 1 ? parts[1].Trim().ToLowerInvariant() : "string";

            switch (t)
            {
                case "datetime":
                case "date": return (name, "global::System.DateTime", false);
                case "int": return (name, "int", false);
                case "double": return (name, "double", false);
                default: return (name, "string", true);
            }
        }

        private sealed record PropSpec(string Name, string Type, bool IsString);

        private sealed record EmitModel(
            string Namespace, string ClassName, string BaseFqn, string SetsCsv,
            bool AddQty, bool AddCtors, string Meta,
            DiagnosticDescriptor? NamingViolation = null, Location? DiagLocation = null,
            PropSpec[]? Props = null, string? DiagArg = null);
    }
}
